### ISSUE TITLE
Create some sort of undead healing kit/potion

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#100]
Only usable on self, does negative damage.

**Comment by tomekk666** [comment]
I have some ideas for items such as this... Embalming Fluid, Rusty Surgeon Tools, Needle and Thread, Skull Charm, Rot Charm, Potion of Inflict X, Potion of Harm, etc.

**Comment by AgonyAunt** [comment]
Nice ideas. Will keep it in mind.

**Comment by AgonyAunt** [comment]
And actually, this ties in with issue #3 which is to add a death themed buffer to the mortuary. Could also make him her merchant selling some of these items.

**Comment by tomekk666** [comment]
That is much more useful, now that the Bazaar/Clerk's Ward has been needlessly overcomplicated into a maze.

**Comment by AgonyAunt** [comment]
In development
