### ISSUE TITLE
Fire and Acid weakness on trolls just too much - remove

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#101]
Considering their LA, and the amount of nasties flinging around fire, its a bit of a killer. Remove it.

**Comment by tomekk666** [comment]
+100% vulnerability to two COMMON (Fire is present in 75% of the areas / Brux's dryads already deal 30+ acid damage as a starting ability) elements is downright overkill, I'm sorry. Its on par with saying 'a vampire can only be killed with a stake in its heart, here's 100% piercing vulnerability'.

**Comment by AgonyAunt** [comment]
@tomekk666 - What was the point of that comment? The GitHib repository is a place for fixing issues, not for writing snarky comments. That can be done on the forums.

**Comment by JivX** [comment]
Just curious, is the vulnerability a binary thing? Like, can it only be 100% or 0%? If not, I could see tacking on a 25% to 30% for both elements if it would be a consideration for lowering their +LA by a point.

**Comment by AgonyAunt** [comment]
Because in the monster manual they have no weakness except it is the only thing that can kill them, but since we can't code for that anyway, it seems best just to completely ignore it all.
