### ISSUE TITLE
Server description

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#105]
I'm flagging you for this Agony, since you're the only one who can really do this.

Right now we're still showing the old "We use Autodownloader" text that we did when I started playing here. Since it shows up in a lot of places (like in the find a server section of the new vault), I think we need to update that to actually say something about the server.

**Comment by AgonyAunt** [comment]
Agreed, i do plan on doing it... just never found where that text is... i think it could be in one of the ini files.

**Comment by AgonyAunt** [comment]
Change made in dev module.
