### ISSUE TITLE
Modify Gauth abilities to match PnP

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#111]
Check PnP description of Gauth, see how it compared.

Also suggestion to change Charm effect to Dominate....

**Comment by AgonyAunt** [comment]
Jiv provided the following:

Source (3.5 MM pg's 26-27) - 

The Gauth, sometimes known as the lesser beholder, is a 4-foot wide orb dominated by a central eye. Six smaller eyes on stalks sprout from the top of its body. It is a rapacious and tyrannical creature that seeks to exact tribute from anything weaker than itself, and often attacks adventurers simply to acquire their wealth.

Eye Rays (Su):

Each of a gauth’s six eye rays resembles a spell cast by an 8th-level caster. Each eye ray has a range of 100 feet and a save DC of 14. The save DCs are Charisma-based. 

The six eye rays include:

Sleep: This works like the spell, except that it affects one creature
with any number of Hit Dice (Willnegates). Gauths like to use this ray
against warriors and other physically powerful creatures.

Inflict Moderate Wounds: This works like the spell,causing 2d8+8 points of damage (Will half ).

Dispel Magic:This works like the targeted dispel function of the spell. The gauth’s dispel check is 1d20+8.

Scorching Ray: This works like the spell, dealing 4d6 points of
fire damage (no save). A Gauth creates only one fiery ray per use of this ability.

Paralysis: The target must succeed on a Fortitude save or be paralyzed for 2d10 minutes.

Exhaustion: This works like the spell ray of exhaustion (no save).

Stunning Gaze (Su): Stun for 1 round, 30 feet, Will DC 14 negates. The save DC is Charisma-based. Any creature meeting the gaze of the gauth’s central eye.

**Comment by JivX** [comment]
I think the focus/time cost to go though and change this from Beholder stalks to Gauth stalks is too high for too little a problem. If anything, just label the Gauth a full fledged Beholder for now and focus on other things? Maybe at some point someone might decide to break this down into two races with different +LA's?

How time consuming is it to make the switch from Charm to Dominate on the eye stalks?

**Comment by AgonyAunt** [comment]
Charm to dominate would be fairly simple and quick. A change to the scripted effect, and change the TLK entries for the race and feat.

Actually, since the eye stalks are controlled by a single script, its fairly simple to modify the lot. Although the Inflict Moderate Wounds on the Gauth is pretty weak and doesn't scale, so i would keep the scaling with that.

**Comment by AgonyAunt** [comment]
Side topic, while at it, consider increasing usable of Mindflayer abilities.

**Comment by AgonyAunt** [comment]
For the moment dropping this idea.
