### ISSUE TITLE
Turn Resistance Feat

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#119]
Since the item property on the tattoo doesn't work, an option would be to create some feats, like Turn Resistance +5, TR +10, TR +15, and make them general feats.

Then hook into the Turn script and check for those feats and adjust turn appropriately.

**Comment by miriamchaturvedi** [comment]
Couldn't you check for the item in inventory within the Turn script as well?

**Comment by AgonyAunt** [comment]
Best to avoid inventory scans wherever possible, they are quite intensive and can fail due to inventory overload or TMI conditions.

**Comment by tomekk666** [comment]
Ugh... no need to make undead feat deprived as well.

**Comment by AgonyAunt** [comment]
No need to give them things for free either @tomekk666

**Comment by AgonyAunt** [comment]
As a solution simply made PCs a bit harder to turn by taking into consideration LA.  Let's see how feedback goes with this change.
