### ISSUE TITLE
Give Efreet a kind of Human Torch 'flame on" feat

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#12]
As WoF doesn't work suggest grant in its place the ability to extend their flames to cause fire damage to people attacking them.

At the same time, while active, apply the flame VFX to the Efreet.

This replaces issue #10 and #11

**Comment by Xndar** [comment]
Okay, so I've written the script and feat. The only thing I can't figure out how to do is how to make it toggle on/off properly. 

Turning the ability on is easy, but removing it is proving to be a pain in the ass. Using the feat a second time will remove the "aura", but not the vfx, even though I've specifically formulated the script to do just that.

**Comment by AgonyAunt** [comment]
Link the aura effect to the visual effect using EffectLinkEffects().  When you remove one, they both get removed.

**Comment by Xndar** [comment]
They are both linked currently in that very manner, and they disapear together when one rests, but not when one casts the spell for the second time, which should dismiss any and all effects to prevent stacking/function as a toggle switch.

**Comment by AgonyAunt** [comment]
Hmm.... so you are talking about casting it when it is already running and that is how the toggle works?

Can you post the script here?

To embed code, wrap the script in three of these ` (the backwards apostrophe, usually top left key on your keyboard below Esc) at the start and end of the script.

**Comment by Xndar** [comment]
``` //::///////////////////////////////////////////////
//:: Efreet Flames
//:: scod_rs_efreetflame
//:: 
//:://////////////////////////////////////////////
/*
    Caster deals 1d6 fire damage to all melee attackers 
    scoring a successful hit.
*/
//:://////////////////////////////////////////////
//:: Created By: Xndar
//:: 
//:://////////////////////////////////////////////
//:: 
#include "x2_inc_spellhook"
#include "x0_i0_spells"
void main()
{

/*
  Spellcast Hook Code
  Added 2003-06-23 by GeorgZ
  If you want to make changes to all spells,
  check x2_inc_spellhook.nss to find out more

*/

    if (!X2PreSpellCastCode())
    {
    // If code within the PreSpellCastHook (i.e. UMD) reports FALSE, do not run this spell
        return;
    }

// End of Spell Cast Hook


    //Declare major variables

    int nDuration = GetCasterLevel(OBJECT_SELF);
    int nMetaMagic = GetMetaMagicFeat();
    int nDamage = d6(1);
    object oTarget = OBJECT_SELF;
    effect eDur = EffectNWN2SpecialEffectFile("fx_balor_fire_aura", oTarget); 
    //PKM OEI 09.29.06 - The following check is to make sure this spell maximizes properly
    effect eShield = eShield = EffectDamageShield(DURATION_TYPE_INSTANT, nDamage, DAMAGE_TYPE_FIRE);


    //effect eDur = EffectVisualEffect(VFX_DUR_CESSATE_POSITIVE);   // NWN1 VFX 

    //Link effects
    effect eLink = EffectLinkEffects(eShield, eDur);


    //eLink = EffectLinkEffects(eLink, eVis);   // NWN1 VFX

    //Fire cast spell at event for the specified target
    SignalEvent(oTarget, EventSpellCastAt(OBJECT_SELF, 1286, FALSE));

    //  *GZ: No longer stack this spell
    if (GetHasSpellEffect(GetSpellId(),oTarget))
    {
         RemoveSpellEffects(GetSpellId(), OBJECT_SELF, oTarget);
         RemoveSEFFromObject(OBJECT_SELF, "fx_balor_fire_aura");
    }

    //Apply the VFX impact and effects
    ApplyEffectToObject(DURATION_TYPE_PERMANENT, eLink, oTarget);
}
```

**Comment by AgonyAunt** [comment]
Hmm.. how are you handling the toggle by the way? I presume no cooldown, just click to activate, click to deactivate?

But what i'm seeing here an instant shield effect is being applied (shouldn't this be a persistent or temporary depending on whether you want it a toggle or duration?).

Then you check for existing effect, and strip it if its there.

Then you apply the linked effect.

In other words, the VFX is always going to be active, but the shield is never going to be active.

What you should do is at the start of the script check to see if the spell effect is present.

If so, remove the effect.  If not, apply it.

**Comment by Xndar** [comment]
I don't think the placing of that function matters, as the Apply Effect function occurs after the SpellEffect check, so it hasn't been applied yet, so it doesn't prevent the spell from being cast. As far as I have tested, the initial casting always works as it should, and removing the actual effects works as it should, but the RemoveSEF function doesn't seem to work.

**Comment by AgonyAunt** [comment]
As i said, you shouldn't need the remove SEF function anyway, they are linked.  Its strange.

But give it a try anyway like i suggested. Failing that, ill give it a try myself.

**Comment by AgonyAunt** [comment]
Just a thought, make this whole thing time based instead of a toggle. Should simplify things.

Make it 1 round/level, instant feat (ie, no casting time), usable unlimited times/day.

**Comment by Xndar** [comment]
Went with your second idea. Set the duration for 24 hours, instant feat, usable unlimited times/day, and arranged the script so that the effects do not stack. 

Is there somewhere on this site that I can upload my work? I've edited the two warlock invocations, and given the Efreeti and Djinni their racial feats (properly scripted).

**Comment by AgonyAunt** [comment]
Nah, we will keep dropbox as our place for code for the moment. I was looking at using GitHub for storing code and pull requests, but its a little complicated, requires everyone to have GitHub software installed, and probably not necessary.

**Comment by AgonyAunt** [comment]
Just remember to include a readme saying which 2da/tlk lines have changed so i can merge easier.

**Comment by Xndar** [comment]
Kay, I'll upload the stuff tomorrow. Are we going to move ahead and try to design the Gatecrasher, or is it still being thought about?

**Comment by AgonyAunt** [comment]
Gatecrasher will go ahead. Implementation might need some tweaking as we hit the feats and think about things more deeply. Especially the manipulate portal one.

**Comment by Xndar** [comment]
I think I might have found an elegant solution to the manipulate portal ability...see my post in the General Builder's Forum

**Comment by Xndar** [comment]
Per my PM, uploaded my 2da/tlks and scripts, with attendant readme.

**Comment by AgonyAunt** [comment]
cool

Will add with next update.

**Comment by AgonyAunt** [comment]
@Xndar - i was impressed you chose the grey dwarf ability for enlarge person, because that doesn't check racial type.  Your reduce person script really doesn't need all the racial checks in it either, as its only usable by the race that gets it, so i will strip that code.

Sloppy coding here: 

`effect eShield = eShield = EffectDamageShield(DURATION_TYPE_INSTANT, nDamage, DAMAGE_TYPE_FIRE);`

Ok, eShield = eShield isn't bad, but the DURATION_TYPE_INSTANT where you should have the Damage Amount is plain bizarre. The second parameter you pass a fixed value when it should be a random constant value of DAMAGE_BONUS_\* type.

Also, not your fault, but lukehall had used a row you had claimed for the new feats and i hadn't noticed, so manually changing those myself.

**Comment by AgonyAunt** [comment]
Also, i've increased the damage. Its now 1d6 + 1 per Efreet level.

**Comment by AgonyAunt** [comment]
And a minor point. When using a feat to call an existing spell, be aware that sometimes scripts might make a call to check for SpellFeatID. If so, it will incorrectly report 0 (because no feat assigned to the spell in spells.2da) or the feat it initially linked to, since you can't assign more than one feat here.

Not normally a problem.  Usually scripts use GetSpellID, but there can be occasions where GetSpellFeatID might be used.

For this reason, its generally better to create new entries in spells.2da, even if you are going to use an existing script, just to make sure there will be no issues with getting feat ID.

Anyway, shouldn't have any impact on your changes here.
