### ISSUE TITLE
Giant weapons are too large

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#124]
Saw one in game for the first time.  Looks like i overdid it on the scaling. Tone it down a little.

**Comment by tomekk666** [comment]
No, don't. >:-[

**Comment by AgonyAunt** [comment]
A little. I promise, and just the clubs...

**Comment by AgonyAunt** [comment]
Oh, apparently not possible. Oh well.
