### ISSUE TITLE
Naming of transitions in sigil "main"

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#126]
The zone for Sigil Main has been split into the two sections of The Great Bazaar and the Clerks Ward, however all the transitions that lead into these areas were not renamed to reflect the split and transitions leading to both are all still named "To Sigil Main."

Understood that this is a low priority, but can they be renamed to reflect which of the two zones into which those transitions lead?

**Comment by miriamchaturvedi** [comment]
Oops, yup, its now on the list.

**Comment by AgonyAunt** [comment]
@Mimi-Techmouse  - maybe i missed it, did you make this change?  If not, assign the issue to me, its silly to ask you to make an updated area when its simpler for me to make the change on my dev box.

**Comment by miriamchaturvedi** [comment]
Uh, no, I don't think I've made this change yet. The issue is all yours.

**Comment by AgonyAunt** [comment]
Editing now.
