### ISSUE TITLE
Summon Dampening issue

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#133]
Just found a little bug with the Summon Spell Dampening power while fooling around in the OOC room:

I used the Dimension Door power to get away from a beast I'd dampened, and it was stuck that way, even though I has rested. I fixed that by re-activating dampening and moving close and then away from it on foot.

Edit: After a little more testing, it seems that anything that 'updates' the summons, including someone shoving them, gets them out of the Dampening-Dimension Door lock.

**Comment by Xndar** [comment]
That is strange...the only thing I can think of is that DD is somehow not triggering the 'on-exit', even though the summons are technically exiting the aura. Maybe the phasing duration needs to be changed to 6 seconds, and the aura needs a heartbeat function to renew the phasing and check if the critter is in the area of effect?

**Comment by Xndar** [comment]
Or, more simply, I could make it so that the aura interferes with dimensional travel...aka make it impossible to cast DDs while the spell is active.

**Comment by AgonyAunt** [comment]
Could work, makes sense if the effect is disrupting summons.  Although its an edge situation anyway.
