### ISSUE TITLE
Infinite Staircase - Ice portal

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#136]
Not a bug with the class really, but in the infinite staircase the portal with the big gear on top next to the stairs to the ice plane doesn't work. The dialog pops up asking if you want to enter and it's level range 2-6 but when you say yes nothing happens. Also I'm still missing textures on my end.

**Comment by Xndar** [comment]
can you give me the tag of the Mechanus WP you used for the Sigil portal, so I can plug it into the convo?

**Comment by AgonyAunt** [comment]
Look in the build module. Its there.
