### ISSUE TITLE
Celestials and Petrification

### ISSUE THREAD

**Issue by Xndar** [AgonyAunt/Sigil-City-of-Doors-PW#138]
According to the MM and every other source I could find, almost all Celestial creatures are immune to petrification, which is currently not the case. The following current PC races would be effected by this, and should receive this immunity:

Hound Archon
Trumpet Archon
Ghaele
Bralani

**Comment by AgonyAunt** [comment]
Ill take it myself if you want to focus on other stuff.

**Comment by AgonyAunt** [comment]
Can't find an existing immunity to petrification feat. Will need to make one.

**Comment by AgonyAunt** [comment]
Considering how rare petrification is on our server, unless someone else wants to tackle this, ill close it as being too minor to deal with.
