### ISSUE TITLE
Succubus needs appearance change ability

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#14]
Request for Succubus to be able to change appearance at will.

Xndar offered to deal with this.

**Comment by Tamamo-no-Mae** [comment]
I feel like suggesting succubi should have a humanoid base appearance and can swap to the succubus appearance at will. Would make it more customizable, at least.

**Comment by AgonyAunt** [comment]
Like vampire then? Two issues - it would mean a fixed base appearance (race) and no changing to other races.  Also any existing succubus would need to do a full rebuild to make this work.

Also, i really wanted to deter too many succubus walking around considering the nature of the RP of certain types of players. Its enough with the Nymphs.  Which is why i chose to got this route. 

Ah, also it has to be a polymorph effect to avoid model issues with chaging appearance (you remember the issue with Vampire Dark Form and it not working?  Would be a double issue with human or tiefling base form, so definitely polymorph.  So no casting or changing items, which is why better to have succubus base form, so when grinding they will be in their natural form.

**Comment by Tamamo-no-Mae** [comment]
Hmm, that makes sense.

**Comment by AgonyAunt** [comment]
Xndar has provided an update for this. Will be in next update.
