### ISSUE TITLE
Plane of Fire Issues

### ISSUE THREAD

**Issue by miriamchaturvedi** [AgonyAunt/Sigil-City-of-Doors-PW#145]
Current bugs / todo list:
- Ferry stops working after some random amount of time
- Slaves don't go away when you tell them to
- No environmental damage
- Get rid of debug text on leaving ferry

**Comment by AgonyAunt** [comment]
Journal issue could be my fault with importing, but other quests are working...

**Comment by AgonyAunt** [comment]
I've removed the fire opal from the foundry, so that's one less thing for you. ;)

**Comment by AgonyAunt** [comment]
About to move your stores to the store area (ps_store_area).

If you are making updates to those areas, delete the stores from them. If you need to edit the stores, use the new version of the area that will be in the next uploaded build module.

**Comment by AgonyAunt** [comment]
Looks like the journal entries not appearing is my fault. Another one you can wipe off your list. Its happening to all quests.

**Comment by miriamchaturvedi** [comment]
Great, list edited accordingly.

**Comment by AgonyAunt** [comment]
Fixes applied.
