### ISSUE TITLE
Static NPCs in Salt areas

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#146]
On the ship and in Toil there are static NPCs.

Replace them with waypoints and edit on-enter scripts to place them. 

Add on-exit script to all salt areas (bar_onareaexit).

**Comment by Xndar** [comment]
Will do this today

**Comment by Xndar** [comment]
Uploaded the fixes, replace the areas as they should now have the appropriate WPs and on-enter/exit triggers in place.

**Comment by Xndar** [comment]
Also be sure to replace Tarek with the new version, as it will otherwise not have the actual conversation applied as it should.

**Comment by AgonyAunt** [comment]
ok, great

**Comment by AgonyAunt** [comment]
Should be fixed now i believe.
