### ISSUE TITLE
Limbo Crash

### ISSUE THREAD

**Issue by AlanLane** [AgonyAunt/Sigil-City-of-Doors-PW#147]
Yesterday, the game crashed 3 times to all players (and in the same moment) during some fight in the stormy beach of the limbo.

Seems like that some memory error appear due to the many VFX.

The crash seems related to the spawn of monster near the cave waypoint.

**Comment by AgonyAunt** [comment]
Thanks for the info.

**Comment by AgonyAunt** [comment]
@Mimi-Techmouse - can you look at this? Perhaps tone down the FX?

**Comment by miriamchaturvedi** [comment]
Yup, will look into it. Was it a very large group of monsters spawning by the cave?

**Comment by AlanLane** [comment]
Yes. With 3 characters in the party and all set to Gatecrasher. But there is something strange with that spawn, since it's the one that crashes the game.

**Comment by AgonyAunt** [comment]
So just this specific spawn.. interesting. Might be worth checking if there is a specific boss or monster that is a problem when spawned that doesn't appear elsewhere... or maybe the spawn point is in a non-walkable area...?

**Comment by miriamchaturvedi** [comment]
Oh they're all in walkable areas, and there's nothing special about that one in particular. But its possible that with some of the larger slaad they're overflowing their space on gatecrasher so the spawn point will need tweaking.
