### ISSUE TITLE
Increase size font of the UI.

### ISSUE THREAD

**Issue by AlanLane** [AgonyAunt/Sigil-City-of-Doors-PW#149]
Since nowaday, computer screen works at high resolution, would be nice to increase the size font of the UI of the chat dialog and the event dialog.

What do you think about it? Would increase the readability of the text.

Feel free to comment it. 

If you agree, I can do the job.

**Comment by AgonyAunt** [comment]
Its possible and perhaps a good idea.  Not too much though, some people may still run in lower resolutions.  And remember, its all widescreen these days, so bigger font means less height, which is not so much bigger than it used to be.  I mean, i'm sure some people still run at 1400x900, which vertically is not so different from 1024x768.

Anyway, if you think you can edit the XML, give it a try and post some screenies. ;)

**Comment by AlanLane** [comment]
I run the game at 1440x900 and found the text a bit little.

We could always start a pool on the board to see how many people run in low resolution. :)

I'll post some screen :)

**Comment by AgonyAunt** [comment]
Good idea.

**Comment by AlanLane** [comment]
![screen](https://cloud.githubusercontent.com/assets/8768715/4549179/cd01605a-4e5b-11e4-9c79-d5a117cd7706.jpg)

This is the result, i've just increased the size of one point, and the readability is better. At least IMHO ^_^

**Comment by AlanLane** [comment]
And i've noticed that the tweaks is working on SCoD too... Weird... i've supposed that UI override was blocked by the nohack script

**Comment by AgonyAunt** [comment]
You can override stuff like GUI without issue. Hence the reason some people use VFX overrides.

**Comment by AlanLane** [comment]
I use VFX overrides too. (With my enhanced/reduced version of spells effects).

I've heard that GUI ovverride can be used to set some macro in the game that would be like cheating... This is why i've thought that GUI Override was blocked :)

**Comment by AgonyAunt** [comment]
Nah, appearance stuff is fine. Its GUI scripts that are protected. So you can't go and place a modified GUI that will give you a button to click that will give you more XP. The button will work, but no script will fire.

**Comment by AlanLane** [comment]
lol, that sounds reasonable ^_^ 

anyway, what do you think about the increased font size?

**Comment by AgonyAunt** [comment]
Looks good, feel free to upload the files to dropbox and make a post in the "What needs to be added to the module" sticky thread in the builders forum.

**Comment by AlanLane** [comment]
Alright :+1: 

[EDIT]
Done.

**Comment by AgonyAunt** [comment]
Also post this here: 

Oh... you mean you didn't change the actual GUI files, but the fontfamily one.

Erm, that could have an impact on a whole range of screens.

Can you just run some extra tests with it?  I'm thinking the Sigis parchment/new reading for one. And the card game for another. Just to make sure your increased fonts don't mess up those screens.

**Comment by AlanLane** [comment]
Since this changing is allowed also by overriding it, I'm actually testing it.

I'm going to check SIGIS parchment and the card game asap.

**Comment by AlanLane** [comment]
Sigis and cards are not affected by this modification.

The PC Tools seems to be glitched. Some button lacks of text, maybe because it's too big and it overflow outside of the button.

**Comment by AgonyAunt** [comment]
Ah ha! Nice catch.

I presume you don't want to go editing tons of XML to rescale the whole PC Tools UI, so maybe you can edit just which font is being used for PC Tools UI.  You know how to do this?

**Comment by AlanLane** [comment]
Yep. I know it :+1: 
I'll do some test with my fontfamily.xml

**Comment by AgonyAunt** [comment]
By the way, since it will work as an override, you can offer via the forums for other people to test your changes as well. Just remember to put warnings that its a work in progress so some things might not look right.

**Comment by AgonyAunt** [comment]
Due to the wide range of issues that may occur with this, i.e: literally having to change a wide number of XML files for it to work with them, ill leave this as an optional use thing. Basically @AlanLane - you can release for public use as an override, we can provide a link to it on the wiki for those who want to use. But we will not integrate into the main module.
