### ISSUE TITLE
Limbo boulder issue - walkmesh or trigger related?

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#153]
Rainbow Prism reports:

Entered the caves. Got stuck in one place when boulder bugged out and appeared on the place where my character stood. Sometimes the boulder do not offer check at all, as if the trigger is not there. Even when they previously activated.

**Comment by miriamchaturvedi** [comment]
The script is supposed to check for PCs in the vicinity before spawning the boulder so it can move them out of the way or apply damage. Will look into it.
