### ISSUE TITLE
Inconsistent DCs on some new racial feats

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#16]
Needs looking into. Not certain if this issue is real or whether UI not reporting correctly.

**Comment by Tamamo-no-Mae** [comment]
I can run through some tests no problem, as long as I know what races need their abilities checked.

**Comment by AgonyAunt** [comment]
Not sure myself. There was the one post on the forums, i should have linked to it here, but just scan back through the posts from last week or so.
Thanks for the help.

**Comment by AgonyAunt** [comment]
Over a month since last info. Closing. Can review if further reports occur.
