### ISSUE TITLE
RP XP - give direct or to different pool?

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#160]
As suggested by Cristel.

**Comment by JivX** [comment]
The only way I have ever seen RP XP done well was over on the ToA/PoS server. 
1. Creatures give sub par XP in nearly all situations.
2. You get a Creature Killing Bonus XP Pool per day. I think it was about 3500ish. 
3. When you RP with other people you got small incremental gains to both Creature Killing Bonus XP Pool and direct XP, in the amount of 35 to 75 per gain.

So you login and grind for a bit till you or your group runs out of Bonus XP. Then you all go back to town and RP for awhile to rebuild your Bonus XP. Then go back out and grind for a bit, rinse and repeat. It really did a fair job of making RP time not seem wasteful even if you're someone who's focused on leveling. 

If something like that doesn't appeal to you then just add it directly to the XP pool. Needless extra pool is unnecessary and RP XP is always a good idea on PW's.

**Comment by ghost** [comment]
I generally prefer the idea of directly giving role-play XP, but then, we get a combat bonus for RP XP stored. Give half directly and half to the single pool? I've not looked at the values yet to know if the amount would be so low as to discourage role-play if any are doing it purely for the experience (though I would hope that isn't the case for anyone).

**Comment by AgonyAunt** [comment]
@SCoD-PhoenixRising - Thanks for the input. Its something i haven't given too much thought to yet, but will keep it in mind.

**Comment by AgonyAunt** [comment]
As i;ve done nothing with this for weeks, and have not made up my mind as to whether its a good idea, and the existing system has been ok for years, closing for now until i become convinced a change is required.
