### ISSUE TITLE
half-fiends/celestials

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#161]
Gain DR 5 instead of DR 10.

See: http://z13.invisionfree.com/nwn2planescape/index.php?showtopic=9885&st=0&#entry22722432

**Comment by Xndar** [comment]
Fixed the entries in the 2das, they are in my latest upload folder in the 2da DB folder. (Xndar Upload DR Hotfix)

**Comment by AgonyAunt** [comment]
Cool.

And apparently the celestials might be able to use their racial feats before they should.
Also report of not seeing history feats, which i didn't think should be possible, unless they mean heritage feats, in which case i would presume they just didn't meet requiremetns.

**Comment by AgonyAunt** [comment]
Apparently the player had confused background feats with history feats, so thats not an issue.

Regarding the half-celestial scripts, i checked the Summon planetar one you provided, there is no level check in it, so of course its usable.

So, check those and resubmit.

**Comment by AgonyAunt** [comment]
Ok, it was just the summon planetar that was open to use from level 1, because you had simply reused the existing script.

I've fixed it, and also created a custom TLK entry so that it will give proper info.

**Comment by AgonyAunt** [comment]
Fixed.
