### ISSUE TITLE
Make plank on astral ship indestructible.

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#162]
As per title

**Comment by AgonyAunt** [comment]
done

**Comment by AlanLane** [comment]
Seems that the wooden plank is missing on the Dead God Rock when the ship fade in at the dock.

**Comment by AgonyAunt** [comment]
Buggeration.

**Comment by AgonyAunt** [comment]
Issue caused by error in 2da.
