### ISSUE TITLE
Arboreal Archer Set Bonus Problems

### ISSUE THREAD

**Issue by ghost** [AgonyAunt/Sigil-City-of-Doors-PW#175]
With the gloves, belt, and bow, the Arboreal Archer's Bow gets:
Greater Weapon Specialization (Longbow) and
Greater Weapon Focus (Longbow)

However, while the in-game description suggests the bonuses these feats provide replace the regular versions, in practice they give the _delta_ between them. That is, GWS gives +2 damage, just like reglar WS. The effect is the same unless the earlier feat is missing.

The bow gives regular WS without the set bonus, and replaces it with GWS with the set bonus. But the effect is the same +2 damage either way, i.e., the upgrade is not actually an upgrade. I assume this was not intentional.

**Comment by AgonyAunt** [comment]
Thanks for the info, one for Cere to fix then.

**Comment by AgonyAunt** [comment]
_Pokes Cere_ Any chance of getting a fix for this?

**Comment by Ceremorph** [comment]
No idea what's happening here. The GWS feat is being granted, but it's not applying the damage. I'm going to guess that GWS actually grants +2 and it stacks on top of WS's +2. I'm going to try that on the script and see if we get any progress.

**Comment by ghost** [comment]
_> I'm going to guess that GWS actually grants +2 and it stacks on top of WS's +2._

Yes, this is exactly how the feats really work (contrary to the in-game description). Sorry if that was not clear from what I wrote above.

**Comment by AgonyAunt** [comment]
Ah, yes. You will need to grant both feats to get the double bonus.
