### ISSUE TITLE
Auto-sorting on collection of items

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#176]
Just something that came out of discussions on Bioware boards.

What if you could select certain containers to fill up with certain types of items when you obtain them?

So gems into a gem bag, etc.

Would require storing object ID on essence to avoid constant inventory scans and checking for containers overflowing, but it might be nice.

What issues might exist? Purchasing items would also be affected, so not good if you want quick access.

Of course, system would be optional and configurable.

**Comment by AgonyAunt** [comment]
Beta version on the server.

**Comment by AlanLane** [comment]
I've noticed a bug. Sometimes items won't be stored in containers and get lost.
If you activate the script on a container it will works.
Then my game crashed and i've rejoined.
And BAM, item lost somewhere in the multiverse.

I'll try to replicate systematically the bug.

**Comment by AgonyAunt** [comment]
Cool, thanks. Thats seems to match other reports we have had, but its rather strange.

**Comment by AgonyAunt** [comment]
As far as i know, all more or less ok now. Some bugs may exist or need some tweaks making but will solve those if they are raised.
