### ISSUE TITLE
Nymph Unearthly Grace - not work in heavy(ish) armour

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#178]
Silly AC obtainable when the lithe nymph is stomping around in full plate _facepalm_

Consider having it work cloth only (or with light armour as well).

Needs changing from just an active feat to one that an also be enabled/disabled on equip/unequip of armour.

**Comment by JivX** [comment]
And the race has a huge LA, so it's not really an issue.

**Comment by AgonyAunt** [comment]
The LA isn't the issue. Nymphs stomping around in full plate is ;)

**Comment by AgonyAunt** [comment]
Fix made.
