### ISSUE TITLE
Infinite staircase - issues

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#181]
Reported by er_nano

as jall finally got her last lvl of gatecrasher i visited the infinite staircase, so here's a small list of oddities/errors:

the walkmesh is blocked in the center, by the blue carpet

two of the stairs (winding staircase and a ''staircase'') lead to the same place, the abyssal maze

the arch with the pillar above it, next to the portal to karasuthra, has no portal

the portal to niflheim may be a bit misleading , as the low lvl zone is mostly a transition zone given the low amount of enemies it has, but the real deal is the castle which is epic, but whatever

i couldnt find portal for the outlands, elysium, brux and oinos. nor for sigil, though not sure if it was ever meant to be one for that.

**Comment by Xndar** [comment]
1) Some of the arches are empty. I believe that one (if by pillar, they meant Obelisk) is reserved for the area Cere is working on.

2) There was never meant to be one for Sigil, and there isn't any need for it if you think about it. All of the portals spit you out at the portal back to sigil in the respective planes anyway.

3) Will fix the walkmesh issue and look at those two stairs.

4) Yeah I knew I was missing a few, will see about adding those.
