### ISSUE TITLE
Consider Natural Spell for Arcane casters and warlocks

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#182]
Requirements? How to make it work? Will FEATOR cover it? Only 2 options here as i recall in 2da, so Still Spell, Silent Spell, and then a third that opens the path to Natural Spell?

**Comment by AgonyAunt** [comment]
All polymorphs would have to be changed to be flagged as wildshapes.

**Comment by LadyLightning** [comment]
Requirements could (and should) be as simple as being of a race which has an alternate form.
In fact, some forms that should really allow spellcasting by default, such as a dragon's ability to
turn into a humanoid (which has hands for somatic and vocal chords for verbal), or the 
vampire's ability to reveal their Dark Aspect (which also can form somatic and verbal components just fine), should arguably get the feat as a bonus feat.

Perhaps there's a way to make a race-specific version that only works with their racial forms, so a dragon can cast spells in humanoid form, but a dragon with druid levels still needs to take the feat to cast spells while in animal form?

Also, I hope I'm allowed to post here, and I hope my posts are helpful and valuable!

**Comment by AgonyAunt** [comment]
Anyone can post here, its one reason for making it public. 

Can't make it work with an alternate feat as the ability itself is hardcoded. All can do its grant Natural Spell to anyone who should have the ability to cast spells while polymorphed. Will consider that. But first the actual spells would need to be changed to be wildshapes and need to consider if there are any issues we could create by doing this.

**Comment by AgonyAunt** [comment]
Decided against this for a number of reasons. Some technical, some RP.
