### ISSUE TITLE
Cloaks with wings

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#187]
Nooooo!!!

I made an announcement: http://z13.invisionfree.com/nwn2planescape/index.php?showtopic=10002

**Comment by AgonyAunt** [comment]
Temp removed the option to modify default items while the problem with crashes is investigated.

@Mimi-Techmouse - Will this also remove this option? Would it only be with default cloaks the wings would appear, or did you do something so that regular cloaks can also  be wings?

**Comment by miriamchaturvedi** [comment]
I just forgot to take them out of the list. I will send you a new version of the appearance lists shortly.

Unless you disable ALL cloak modification, they will be available until they're taken out of the appearance changer lists.

**Comment by AgonyAunt** [comment]
Presume this is now fixed. Closing.
