### ISSUE TITLE
Armor update broke my character

### ISSUE THREAD

**Issue by ghost** [AgonyAunt/Sigil-City-of-Doors-PW#188]
While I appreciate the new options, the full-body skintight suit my character was wearing got replaced by something a little more... um... revealing.

Old appearance:

![nwn2_ss_110114_080921-cop](https://cloud.githubusercontent.com/assets/9448409/4919042/c06574d8-64f6-11e4-9902-1cfabc574bb5.png)

Looked through the item appearance changer and the old model simply does not appear to be available, and there doesn't appear to be anything that is really a close approximation.

**Comment by AgonyAunt** [comment]
@Mimi-Techmouse - what you think? Another overriden armour? Is that one of those you included?

**Comment by AgonyAunt** [comment]
@n3y28eaeju - thank you so much for taking the time to raise the issue here. So much easier to track problems this way.

**Comment by miriamchaturvedi** [comment]
Dang it, looks like one of the old armor sets slipped through the cracks. What's the new appearance?

**Comment by ghost** [comment]
A topless thong.

**Comment by AgonyAunt** [comment]
LOL.... what is the account name/name of character. Ill take a look and see if i can revert it.

**Comment by ghost** [comment]
eidolon/Sahariel. She has two sets of robes in her inventory that should look like the above (one of them no longer has the same appearance because I tried to fix it with the appearance changer)... she's currently wearing a Cleric's Robe out of embarassment and shame.

**Comment by AgonyAunt** [comment]
Ah, is going to be hard finding those items.  Next time you log off, before you do so, equip the armour, it will help finding it... or at least put it in the first slot in your inventory. Let me know when its done, ill try and jump as quick as possible to check it out.

**Comment by ghost** [comment]
Okay, they are in the first two slots of my inventory. "Sneaky Robes" and "Shadow Silk".

**Comment by AgonyAunt** [comment]
Excellent, thanks.

**Comment by AgonyAunt** [comment]
Got it, armour type 181, and cloth base type i think.

Can take a look next chance i get... but as it is human female... that means updating the 1Gb HAK :(

**Comment by miriamchaturvedi** [comment]
Female human and elf seem to be missing that armor set. There's a few other oddities that crept in as well - do you want me to fix them if we we're updating again anyway?

**Comment by AgonyAunt** [comment]
Would be great, yeah. Although don't package them in HAKs, just zip up the models/textures that need to replaced, ill do the packing.

**Comment by miriamchaturvedi** [comment]
Ok

**Comment by AgonyAunt** [comment]
Assigning to Mimi while she packages the appropriate files.

**Comment by ghost** [comment]
Any progress on this?

**Comment by miriamchaturvedi** [comment]
Sort of. . . I know what needs to be done, and its half way compiled, I just haven't finalized the changes yet.

**Comment by AgonyAunt** [comment]
@Mimi-Techmouse - you can close all issues which you have provided changes for, update going in soon.

**Comment by ghost** [comment]
Is this actually fixed? My armor's appearance hasn't reverted to the old appearance, and I still can't find the old appearance in the appearance changer.

**Comment by AgonyAunt** [comment]
Its now a new entry... it may be that for some reason its not showing.

Mimi?

**Comment by miriamchaturvedi** [comment]
Its a new entry. I guess a new entry will need to be added to the appearance changer list as well in order to reach it.

**Comment by AgonyAunt** [comment]
Should be fixed now.

**Comment by ghost** [comment]
\o/ Yay! Verified in game.

**Comment by AgonyAunt** [comment]
Excellent!
