### ISSUE TITLE
Undead should have d12 Hitdice

### ISSUE THREAD

**Issue by tomekk666** [AgonyAunt/Sigil-City-of-Doors-PW#19]
As per PnP, each level they take gives them a d12 HD worth of HP to compensate for their lack of Constitution bonuses.

**Comment by AgonyAunt** [comment]
Not possible really. A hack could provide a work around but would play hells with the relevel script.

I thought long and hard about the whole issue of undead CON and hit dice before making a decision on this. In the end considering their immunities and bonuses, i felt that the lower HP was compensated.

As a side note, any further improvement in Undead HP situation would require an increase in LA to offset the increased power.

**Comment by tomekk666** [comment]
Those big bonuses can be replicated by two wands... it doesn't really offset the fact that they will end up with half as many hitpoints as everyone else.

**Comment by AgonyAunt** [comment]
Maybe, if they are either a wizard or have UMD. Its an advantage every character can have regardless of race. I'm not making a change on some races based on an argument that applies to all races.

**Comment by tomekk666** [comment]
...so the thing that makes them unique is easily replicable yet you'll still keep them weak because of it? Ok.

**Comment by AgonyAunt** [comment]
Easily if you invest in UMD or are a Cleric i suppose, thats the point, you have to invest to get those things. And bringing OP Cleric spells into a discussion is not a good way to bolster it. Anyway, decision is final on this.
