### ISSUE TITLE
Appearance Changer causing server crashes

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#190]
cryptc also reported a server crash

```
I got one of the quiver outfits in civic festhall
10:46   cryptc  and I tried the belt change thing
10:46   cryptc  I could change it just fine
10:46   cryptc  but then I picked armor parts after that, and server hung
10:46   cryptc  lost the quiver thing so didn't have it to retest from ooc room immediately, so leaving it for you to make sure it's safe if you keep belt thing in there
```

I think it might be best if we remove these options from the convo until it can get further testing.

What you think?

**Comment by AgonyAunt** [comment]
Icelander also reported being able to crash the server - although they say its been happening to them for days.

**Comment by AgonyAunt** [comment]
Also, removed options for default parts changing while this issue is investigated.

**Comment by AgonyAunt** [comment]
Ill throw this in as well from Mander

```
Another big glitch, Half-Ogres, Orogs and Gray Orcs now cannot pick any of the armor visual types but the two categories ACME and DCMB, as if they were a non humanoid model.
```

Also a second report of armour stacking and renaming to armour.

I may have to do a full revert of the xp_craft stuff if this happened after today's update where i removed the "default" modification options.

I guess the former problem occurs because you started adding race specific options, so the other custom races got left out?  Anyway, that's a lesser issue and we can live with it for a while while you figure it out... but armour duplication, thats a nasty one.

**Comment by miriamchaturvedi** [comment]
Nope, poor little orcs just accidentally got left out in the cold. This should be an easy fix.

As for the server crashing - I'm pretty sure the server has always suffered whenever multiple people were flipping through appearances as fast as possible (and EVERYONE does it as fast as possible). Right now its hard to find a time when 2+ people aren't doing it at the same time, too. 

I can't comment right now as to whether or not it would be the in-armor belt/cloak/boots, etc. putting more stress on the server. I've run it fine in smaller test environments before, but never with more than 5 people on. There's nothing particularly special about the code or the armor pieces themselves, though.

**Comment by AgonyAunt** [comment]
Right, makes sense

**Comment by AgonyAunt** [comment]
Closing this then. Let's see how things go.
