### ISSUE TITLE
Rakshasa - DR and SR not properly applied

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#193]
```
Seems neither the DR or the SR are properly applied. I saw the race and was excited to try- but it seems buggy still in that regard. Very VERY cool stuff, just wanted to heads up that even after I talked to styx oarsman to "fix" character, things were messy.
```

**Comment by AgonyAunt** [comment]
Guess Arcanaloth also needs checking then.

**Comment by AgonyAunt** [comment]
Also asked PhantomHermit how they can determine its not applying and whether activating the feat solves it.
Pointed out that most slashing weapons are also piercing (eg: Longsword, Shortsword, etc).

**Comment by Xndar** [comment]
Easy fix...Rakshasa and Arcanaloth are getting the right feats I don't think. Just noticed when I tried to roll Arcanaloth that it was getting the Rakshasa feat.

**Comment by Xndar** [comment]
Aren't\* rather

**Comment by Xndar** [comment]
EDIT: Rakshasas don't get the proper "Properties" feat at all, while Arcanaloths get the Rakshasa feat. Seems like there was a numbering error in implementation, as I double-checked my .2das and the numbers match up properly.

**Comment by Xndar** [comment]
I think the issue is that both properties feats used the same 'Constant', which I have fixed...odd though, as it wasn't an issue in testing at all.

**Comment by AgonyAunt** [comment]
Added, will be in shortly.
