### ISSUE TITLE
Arcanaloth gets Rakshasa racial feat

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#195]
As title

**Comment by Xndar** [comment]
Please see forum PM, I'm not sure wtf is causing this, but from what I can tell in the 2das, there is no reason for the races to be getting the wrong feats.

**Comment by Xndar** [comment]
NM, found the issue. Someone forgot to re-number the feat.2da entries after copy-pasting

**Comment by AgonyAunt** [comment]
This is the same problem as #193 - closing
