### ISSUE TITLE
Minotaur leathers do not display corrrectly

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#20]
Possibly a wrong setting. Otherwise its a model issue.

On related topic, there is a Hill Giant armour missing an icon. Fix at same time.

**Comment by tomekk666** [comment]
They also lack the armored appearance.

**Comment by AgonyAunt** [comment]
Thanks for noting

**Comment by AgonyAunt** [comment]
Fixed.
