### ISSUE TITLE
New? Or old armours... 4 feet!

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#201]
So, this player reported having 4 feet.

Seems to happen with two armours.

Any ideas @Mimi-Techmouse?

![screenshot from 2014-11-14 23 28 47](https://cloud.githubusercontent.com/assets/8188251/5053109/0b38b7d2-6c58-11e4-8f6f-4753ecc1e0ee.png)

![screenshot from 2014-11-14 23 28 40](https://cloud.githubusercontent.com/assets/8188251/5053111/14a05f82-6c58-11e4-8688-18fdd6be61cc.png)

Doesn't make any different if wearing boots or not, still get 4 feet. Switching to other body armours and problem goes away.

**Comment by miriamchaturvedi** [comment]
They just need to remove the default boots, or use invisible shoes. We had outfits like this before which included feet / hands for seamless transitions at the wrists and ankles.

**Comment by AgonyAunt** [comment]
Hmm, thought we tried this.

But ok, we will put it on a back burner for now.
