### ISSUE TITLE
Faction Billboards

### ISSUE THREAD

**Issue by miriamchaturvedi** [AgonyAunt/Sigil-City-of-Doors-PW#206]
From this thread: http://z13.invisionfree.com/nwn2planescape/index.php?showtopic=10106

Create billboards for in game faction announcements.

**Comment by AgonyAunt** [comment]
Is someone willing to work on this? For the moment, i'm not. And we don't even have all faction HQs, so until that is in, i can't see this being acceptable.

Objections to closing this issue until such a time as someone is willing to implement?

**Comment by miriamchaturvedi** [comment]
I thought we just wanted to keep it kicking around until there was time. I don't mind theoretically working on it in the future.

**Comment by AgonyAunt** [comment]
Fair enough, then ill close. I don't like keeping issues open when there is nothing specific planned. As times change, so does the player base and direction the server is going.
