### ISSUE TITLE
Placeables for houses

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#208]
Neephra wants these adding...

http://www.nexusmods.com/neverwinter2/mods/960/?tab=2&navtag=http%3A%2F%2Fwww.nexusmods.com%2Fneverwinter2%2Fajax%2Fmodfiles%2F%3Fid%3D960&pUp=1

**Comment by AgonyAunt** [comment]
@Mimi-Techmouse - you still working on adding stuff to HAKs?

**Comment by miriamchaturvedi** [comment]
I think those placeables look like fun, but I thought you were uncertain about adding them all?

Either way, I wasn't planning on touching placeables in a while, no.

**Comment by AgonyAunt** [comment]
Ok, then we will close.
