### ISSUE TITLE
Male pixie - wrong feats

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#209]
Pixie - Male gets wrong feats, it actually gets human feats. The female version has correct feat selection, but the male one is just worthless tosser currently. Credits to Emptyboxes for spotting it.

**Comment by ghost** [comment]
I could probably just take a look at the female feats and set those up for the males if it's not taken care of already, right? Or potentially, the pixie males don't have the correct configuration. Of course, it's now looking a bit difficult for a newb, but I'll still try to find it.

**Comment by AgonyAunt** [comment]
As you saw last night during out chat, the feats given is defined by racialsubtypes.2da, so its just an incorrect entry there. They should have the same value as the female.

Its a minor change, so ill fix that myself.

We need to find you something else, something a little more interesting.

**Comment by ghost** [comment]
Will do. I had actually noticed, as I mentioned in Skype, the 2da issue, but wasn't sure it if was the only edit needed.

**Comment by AgonyAunt** [comment]
Done
