### ISSUE TITLE
Succubus and others change self feat

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#210]
Make it so that form is selectable - probably via convo

**Comment by AgonyAunt** [comment]
@SCoD-PhoenixRising  - this one might be interesting.

Currently the script is set to produce a random form. Ideally it needs replacing with a script that fires a convo asking which form you would like, and that calls another script that sets your form based on choice.

Fancy taking a shot at it?

**Comment by ghost** [comment]
I can certainly try.

**Comment by ghost** [comment]
Something else. The RemoveExtraHitPoints function isn't working. While the function looks to be correct, in-game, I've noticed it doesn't work, and I can build up 100 or even 200 extra hit points.

**Comment by AgonyAunt** [comment]
I guess this is in limbo. Last contant with Phoenix as i recall was that they were not moving with it. Will unassign for the moment, perhaps someone else can take this on.
