### ISSUE TITLE
Neerepha house

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#211]
Request for a player house in Clerk's Ward

```
Oh, and I forgot: my house is literally ready. Of course I also have enough money to pay it, but I would like to know if it is possible to have it located here (see the screenshots). 
http://i1375.photobucket.com/albums/ag453/Neerepha/NWN2_SS_112814_170856_zpsb09e848f.jpg

http://i1375.photobucket.com/albums/ag453/Neerepha/NWN2_SS_112814_170932_zpsefd7cdce.jpg

If it is available, that would be great. It's an easy place to spot for other players, since it is next the Hall of Records, and it has a doorway and an upper floor exactly like my house. I also have an IC reason to have it right there, than I can provide if needed. (but it is a looooong story, so I'll spare you that for now). Otherwise I had to change some IC plans I have and I'd appreciate to have some time to think about them before the uploading. Thank you!
```

@Mimi-Techmouse - could you handle connecting it? Otherwise i'm liable to break the walkmesh again.

**Comment by AgonyAunt** [comment]
Ill pass on the link for the house itself when i get it.

**Comment by miriamchaturvedi** [comment]
Ok. Forum message is better as I always forget to check github here. .

**Comment by AgonyAunt** [comment]
Grrrr... this is meant to be a better solution that forums.

**Comment by miriamchaturvedi** [comment]
I use it to keep track of my todo list! I just don't check more than once a week. . .

**Comment by AgonyAunt** [comment]
[QUOTE]Hello AA,

I'm finally done with my house! But I can't make the Kemo scripts work properly, or at least, I don't know if they are broken or not, because every time I try to sit, the PC remains stuck in the chair. Please check them!
As I have already told you, I would like that house next to the Hall of Records (using the door in this [URL=http://s1375.photobucket.com/user/Neerepha/media/NWN2_SS_112814_170932_zpsefd7cdce.jpg.html?o=1]screen[/URL]). If due to any walkmesh issue I can't take it, please contact me. As I have already told you, that one is perfect for its structure and my own IC reasons.
I would also have two keys, since I must give one to someone.

Thank you very much!

http://www.4shared.com/get/rk6t4Gwaba/Neerephas_House.html[/QUOTE]

**Comment by AgonyAunt** [comment]
Apparently also a transition from the lower floor to the upper is not work.

**Comment by miriamchaturvedi** [comment]
Uh, any chance of getting a version not uploaded on a site I have to sign in to?

**Comment by AgonyAunt** [comment]
Ah, bad neerepha. Ill poke them.

**Comment by AgonyAunt** [comment]
Dropbox link : https://www.dropbox.com/s/fmi7gf5yy22tk6p/Neerepha's%20House.mod?dl=0

**Comment by miriamchaturvedi** [comment]
Great, that worked. She split it into two areas for some reason, I'm assuming it should be merged as appropriate?

**Comment by AgonyAunt** [comment]
For a player house, ideally. Depends on whether you want to go to the effort.

**Comment by miriamchaturvedi** [comment]
Uploading the house now. The two areas have been merged into one. A key has also been provided.

I did not touch the kemo scripts.

**Comment by AgonyAunt** [comment]
Great

Will reopen and assign to me for update.

**Comment by Neerepha** [comment]
Well, to be honest the areas were divided because I wanted different music ambients as well... I completely forgot about this place and I am sorry, otherwise I'd said it earlier. I've wrote Mimi a PM about it, asking for additional changing due to this merge, and I am sorry as well this thing got so complicated for stupid things.

**Comment by AgonyAunt** [comment]
[QUOTE]And I know you will kill me because I've already sent you too many PMs today, but...
I've noticed now, and just now, that Mimi changed my house merging the first and second floor. Now, the two areas were meant to be separated with different background musics suiting each floor. I would like to have them back, separated as they were (I can send you the link again where to download the module), OR I have to ask you to change few things:
Rename the area: because the area1 was named Neerepha's House - Ground Floor. And you can see it would be pointless to have now an area called "ground floor" which also names the upper floor, because floors have been merged.
Change music: the second floor had the NX1 - Mulsantir as background music, which I would to have added as nighttime music. I am not sure if nighttime music works indoors, so you can skip this point if it doesn't.

I'm really sorry to bother you like this today. Next time ask me if you don't know how to proceed, though  :P [/QUOTE]

**Comment by miriamchaturvedi** [comment]
Small areas really shouldn't be split up into different areas by floor, it takes up more space in the module and makes for a harder to navigate area list. Player houses especially should be one area, the way we have things organized.

**Comment by Neerepha** [comment]
Fine, fine, then just set the area name simply as "Neerepha's House", please. And sorry, I didn't know about this.

**Comment by Neerepha** [comment]
I've found few issues with my house module edited by Mimi (no water in the tub, two doors at bathroom entrance) and I've also modified the area name and the music. I've painted the water, but I still can't see it when I try the module, and I really can't understand why.

https://www.dropbox.com/s/opsysrhzdk41r75/Neerepha%27s%20House%20edited.mod?dl=0

**Comment by AgonyAunt** [comment]
@Mimi-Techmouse - JFYI, removed the floating water and the double door.  

Didn't notice the comment about no water  in the tub. This is a tricky one, we have had this before. In the end had to get another builder to try it to make it work.

Any ideas Mimi?

**Comment by miriamchaturvedi** [comment]
The floating water came from the previous water in the tub. You just have to paint water in the tub and rebake.

**Comment by Neerepha** [comment]
I painted it already, perhaps I forgot to bake after. However, I've done it and checked: it works now. 
https://www.dropbox.com/s/opsysrhzdk41r75/Neerepha%27s%20House%20edited.mod?dl=0 <- you can find the fixed version here, if you want to spare you time. (It has the same name of the previous one, don't be afraid to overwrite it)

**Comment by AgonyAunt** [comment]
Ah, didn't notice this... otherwise could have added it today. Next update ;)

**Comment by AgonyAunt** [comment]
Oh right, i got it now after your PM. I still haven't added it. Sorry.

**Comment by AgonyAunt** [comment]
Added to build module, will be up soon.
