### ISSUE TITLE
Grain of Salt quest never gets marked as complete

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#217]
Very minor-

The "Grain of Salt" quest never gets marked as complete. (It works, but never moves out of the current quests folder). Unless there is more to the quest than I am aware.

**Comment by Ceremorph** [comment]
Looking through the bug list, this one would probably be easier to change at your end Agony. It just involves opening the Journal and checking the last item in this quest as an endpoint.
