### ISSUE TITLE
Add Golden Bariaur Inn

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#226]
And it's done! I have also put some NPCs there, I hope this won't be a problem. The walkmeshes are working and everything looks fine to me. I would like you to modify the barman in order to make him sell waiters contracts, so people can easily roleplay that they are served. You may also add the doorman, a Bariaur named Goldmane, which gives the name to the inn. I couldn't pick up Bariaur as race for NPCs, I don't know why.

https://www.dropbox.com/s/d4xjvs87ydh8tgv/The%20Golden%20Bariaur.mod?dl=0

**Comment by Neerepha** [comment]
Bariaur Goldmane has been added, fixed a couple of minor things, changed voices according to each character (don't know if useful). Please keep the NPCs positions, as well as the different areas (at least keep divided the tavern from the inn area: if you feel the urge to merge something just merge the First and Second Floor.)

**Comment by AgonyAunt** [comment]
[QUOTE]https://www.dropbox.com/s/wpg1xst22w87fbr/The%20Golden%20Bariaur%20%28fixed%29.mod?dl=0 

Here the fixed version! I've also noticed a couple of glitches more and I've fixed them. I also added the Bariaur (I've understood how to do it >_>)
May I contact Mimi as well? I would like to make the rooms buyable for real, like the ones in the Plane of Fire!

[QUOTE]

**Comment by AgonyAunt** [comment]
Oh, try to keep the different areas in the module, because each one has a specific music that suits the ambient. And please also mind to spawn the NPCs where I placed them. Sorry, I tend to be fussy >_<

**Comment by Neerepha** [comment]
Sent a PM to Mimi asking her to add the same script the inn in the Plane of Fire has. (making the rooms really rentable)

**Comment by miriamchaturvedi** [comment]
Sure, can do. How do you want to handle the order of who does what, AgonyAunt?

**Comment by miriamchaturvedi** [comment]
Oh, also, lovely areas.

**Comment by Neerepha** [comment]
Thank you a lot, Mimi.

**Comment by AgonyAunt** [comment]
@Mimi-Techmouse - If you can handle the final tweaks then ill get it added to the module.

**Comment by miriamchaturvedi** [comment]
Ok.

**Comment by miriamchaturvedi** [comment]
Uh, Neerepha, does not moving the NPCs mean you don't even want them to walk around? Because it would be fun if they walked around and had conversations.

Also, since this is the "celestials-only" bar in Sigil, I'm thinking the NPCs should probably be at least snooty to tieflings.

**Comment by AgonyAunt** [comment]
@Mimi-Techmouse -  not certain if people get email notifications on updates, but i think they definitely do if you use the AT symbol, so @Neerepha 

Not an expert at GitHub...

**Comment by Neerepha** [comment]
Uhm, alright, let them move but the barman, the woman dressed in white and the receptionist. I would also like Milich to stop and stare at the plant if he's going to move too.

**Comment by AgonyAunt** [comment]
Added.
