### ISSUE TITLE
Quake's Place - by Serena

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#228]
[QUOTE]Just (barely) in time for the Xaos month!
I've shared on dropbox the finished module for the pub together with some NPC's blueprints I made, hope it works fine!

https://www.dropbox.com/sh/x4ftfgwau8pxs6n/AADDgjEEzXwEvmLwbn4ue2kua?dl=0

Among the npcs there's also Quake herself, which I think would be nice to have spawning randomly at one of the two bar areas!

Let me know how it goes :D  

[QUOTE]How about you create the NPCs and we handle the spawning and placement?

Perhaps since it is the Xaos put, we don't have the same NPCs spawn all the time like most areas, we add a random element.

[QUOTE]Hello!
The xaos pub module is almost ready, but... should put NPC in it? I honestly have never tried, so I really believe it would be better if someone who knows what they're doing did it, but if needed I can make an attempt![/QUOTE]
[/QUOTE]
[/QUOTE]

**Comment by miriamchaturvedi** [comment]
Is this The Hive itself, or something else?

**Comment by SerenaSV** [comment]
Yes, it should be a tavern in the Hive!
 Exact location is unimportant as it tends to... change!

Edit:
updated the npc's blueprints with some convos, ERF replaced!
Also, if someone could allow Quake to sell drinks and food would be awesome

**Comment by miriamchaturvedi** [comment]
No, no, as in "The Hive" - the bar that is the Xaos headquarters. Nice areas, either way.

**Comment by SerenaSV** [comment]
Oh right, sorry! 
Honestly, at first I thought that by working on the Xaos HQ I was indeed going to make The Hive, but then on the Factol Manifesto the only mentioned place was Quake's pub... I really don't know if it's the same place o.o it doesn't seem so...

**Comment by miriamchaturvedi** [comment]
Wierd, I thought I found details for The Hive in the Factol's Manifesto. Oh well.

**Comment by AgonyAunt** [comment]
Yeah, also thought it was Quake's Place as well... so seems good.

**Comment by SerenaSV** [comment]
Yup, as they put it on both the Mimir and the Manifesto, The Hive is another "district" inside the Hive Ward, and would be indeed the real Xaos HQ. But then, talking about houses used by the faction, they give all the info and plans about Quake's Place... 
On the bright side... maybe adding an interior is slightly more comfortable than adding a whole new district to the Hive Ward?

**Comment by AgonyAunt** [comment]
Agreed

**Comment by miriamchaturvedi** [comment]
Agony, would you like me to give it a random door transition and get it ready for adding to the module, or are you working on it already? I'm hoping to get in a few hours of toolsetting in the next few days, and could take care of it and the Golden Bariaur then.

**Comment by AgonyAunt** [comment]
Not touched it at all, so whatever you can do would be great.

I've had zero time in toolset in the last week or so, but just one more day of work, then i'm golden.

**Comment by AgonyAunt** [comment]
In with the next update.
