### ISSUE TITLE
Celestial Torc and set.

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#230]
When you have al the items. And put them al together the Celestial Torc(Necklace) feat: Good DOmain Powers disapears and get replaced with +6 vs Feat (Also...the +6 vs Fear does not disapear when you take the set apart again, it remains on the Necklace. 

http://z13.invisionfree.com/nwn2planescape/index.php?showtopic=10257&st=0&#last

**Comment by Ceremorph** [comment]
I think he must have somehow had a very very old version of the torc. The current standard enchants on the torc by itself are +4 AC, Save vs. Fear +6, and LG only. The good domain powers were taken off the torc a long long time ago.
