### ISSUE TITLE
Armor magically morphs into belts

### ISSUE THREAD

**Issue by miriamchaturvedi** [AgonyAunt/Sigil-City-of-Doors-PW#232]
This was reported by Xndar and others a while back, and then it seemed to clear up. Then Forgotten Dreamer had the same bug happen to him the other day.

Basically, a set of armor turns into 100's of stacked belts for no reason.

I have an idea as to what may be causing this, and am making this issue to remind me to look into it.

**Comment by AgonyAunt** [comment]
Bizarre! Must be something to do with the appearance changer but why and how... that's just bizarre. Could be some sort of hardcoded condition.

Perhaps the only fix would be to check stack size and base item type of initial item, and then compare with the created item. If different, give error message, then revert.

**Comment by miriamchaturvedi** [comment]
I think it might be a line of code I left in when I was trying to enable belts on previously un-enabled ouftis. .  .

**Comment by miriamchaturvedi** [comment]
It is not what I thought it was. . .so, still a problem, but no solution yet.
