### ISSUE TITLE
Possible Plane of Fire issues

### ISSUE THREAD

**Issue by miriamchaturvedi** [AgonyAunt/Sigil-City-of-Doors-PW#233]
Including:
- No monsters?
- Wierdness with people sometimes being stuck on the boat (usually after the server has been up a while)
- Possible bugs with the elemental damage script.

**Comment by AgonyAunt** [comment]
So nice to see people logging their own issues ;)

**Comment by Ceremorph** [comment]
Mimi, is this complete?

**Comment by miriamchaturvedi** [comment]
Nope. Not touched yet.

. . and don't you dare close it. :P
