### ISSUE TITLE
Hideous Blow + Hellfire blast - damage every round

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#243]
Hello. Problem here! It seems that Warlock Buddy 
is applying Hideous Blow every round, even out of 
combat. This is normally not a problem, but with
Hellfire Blast active, it's ~damaging~ you every 
round, even while you're not fighting! Is it possible
that Hellfire Blast is damaging the player on cast,
rather than on-hit? If so, would it be possible to fix
it with Hideous Blow? I see absolutely no reason 
why I should be taking damage every few seconds,
just because the two modes are toggled on at the 
same time.

**Comment by AgonyAunt** [comment]
Not sure about this one. Might be a little tricky.

**Comment by AgonyAunt** [comment]
Can't think of a simple fix. Unless someone else can figure out how to handle this ill close it for now.

**Comment by AgonyAunt** [comment]
Issue has been raised again. Will try and rethink it.

**Comment by Electrohydra** [comment]
I'm looking into trying out a few challenges, I could take a look at this if I had the current code.

**Comment by AgonyAunt** [comment]
@Electrohydra - Code is in the build module, which i believe you should have access to now.

**Comment by AgonyAunt** [comment]
Finding the right code might be a challenge actually... there are layers and layers of function calls with the warlock blast. Its not something i think you want to be trying to cut your teeth on. But give it a look if you want.

**Comment by Electrohydra** [comment]
If I have access I can't figure out where I find it. I see only the readme in the code section.

**Comment by AgonyAunt** [comment]
Someone else will have to take now.

**Comment by Electrohydra** [comment]
Still looking into it, but you're right that it's one nasty piece of work.

**Comment by miriamchaturvedi** [comment]
I think I found the code the other day while working on the fellblade. I'll post the name of the script if Electrohydra's interested.

**Comment by miriamchaturvedi** [comment]
Or not, I guess he found it. :P

**Comment by Electrohydra** [comment]
Actually the code I sent you is for another thing. Though I DO think I found how to fix this bug as well. I made the Warlock Buddy hideous blow last an extra 0.1 seconds, and to check if the caster still had a Hideous Blow readied before doing Hellfire damage. If he does, don't do the damage.

Scripts to change are both nw_s0_ihideousb1.NCS/.NSS

The fix is also highly tentative. It should work in theory, but I haven't tested it.

**Comment by Electrohydra** [comment]
It's not doing damage every round anymore, but still doing damage twice per hit when in combat. I think I know how to fix this, I'll get it done probably for next update.

**Comment by Electrohydra** [comment]
"Would it be possible to apply the correct caster level to the Hellfire Shield ability? I've made the mistake of turning it on in the Abyss a couple of times and successfully had it resisted by everything, and my face melted half-off. " Also to check out for.
