### ISSUE TITLE
Arcanaloth DR Issue

### ISSUE THREAD

**Issue by Xndar** [AgonyAunt/Sigil-City-of-Doors-PW#247]
I've confirmed this IG with my 'loth...DR just vanishes on rest after having cast stoneskin. Going to try setting the feat to active as well as persistent, to see if this for some reason is the root of the issue.

**Comment by Xndar** [comment]
Nope, resting after casting stoneskin still removes the racial DR entirely. Will check both the spell scripts to see what is possibly conflicting.

**Comment by Xndar** [comment]
The issue also applies to Rakshasa. I think the problem is that, for whatever reason, stoneskin overrides pre-existing DR when cast. When removed, the rest of the DR feat's properties (ie, the rest of the creature properties) are still in effect, so the feat's script won't reset the DR even if manually activated.

Likely this is going to require splitting the DR from the rest of the creature properties and making them their own feats, which will be a pain for any existing Rakshasa or Arcanoloth toons. Will make a note again once this has been confirmed as working.

**Comment by AgonyAunt** [comment]
Ok. It shouldn't be a biggie though. If you add a new feat to the racial 2da existing ones will get the new feat when they next level up automatically.

**Comment by AgonyAunt** [comment]
As I understand, this is not an issue, it was just icon disappearing.
