### ISSUE TITLE
Change ownership of Rhistel's shop to Tald

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#258]

**Comment by SerenaSV** [comment]
New area, door and sign name: Tald's Workshop

Sign description:
Formerly known as the Sunken Flagon, later the property of an enchanter.

Now, this unassuming abode is home to a tall, private man. Curiously, unlike the rest of the area, there are absolutely no cats to be seen anywhere near the house.

**Comment by SerenaSV** [comment]
I'll be trying to complete the trade today, hadn't the chance until now unfortunately :(

**Comment by AgonyAunt** [comment]
Yeah, Tald sent me the details in a PM, but thanks anyway.

**Comment by SerenaSV** [comment]
Great! Also, deal was finally concluded! (Now I will just wait for my house in the meantime :D)

**Comment by AgonyAunt** [comment]
Done. New key to be gained from DM (and of course payment). Old key will still work on old house, you can trash it or hand it over. However, in DM client new versions of the key will be named Tald's key and your new house key will be called Rhistel's New House Key.

**Comment by SerenaSV** [comment]
Perfect, thank you so much! 
I already handed Tald's player both keys in my possession, so they should be fine.
I will look for a DM to get my keys and proceed with payment!
