### ISSUE TITLE
Jagged Tooth doesn't work on druid polymorphs

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#264]
Guess the changes made do not consider whether the target is an old style creature or its applying only Improved Critical for the new weapon types.

Make sure it applies for all weapon types.

Also, you may have noticed it gave the improved critical feats on the creature hide in my original version. This is because keen does not seem to work properly on (old style) creature weapons.

At least i think that is it... i might be misremembering something here.

**Comment by Ceremorph** [comment]
Can you look at the script Agony? All that was left in, just as an else at the end if the new ones weren't found. I figure you're more likely to catch the issue than I am.

**Comment by AgonyAunt** [comment]
Ok, taking it.

**Comment by AgonyAunt** [comment]
I think it was working... i think they person who reported was getting the message that it didn't work because that was triggering after not finding any new CWs, but the script would still run and work fine after that.

Anyway, i've moved the error message and changed the requirements for it to fire, hopefully that will fix it.
