### ISSUE TITLE
Serena - house fix

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#265]
https://www.dropbox.com/s/apswh027faytxoa/Rhistel%27s%20workshop%20fixed.erf?dl=0

**Comment by AgonyAunt** [comment]
Added

**Comment by SerenaSV** [comment]
I'm so sorry, but seems like even with the upload of the fixed module, the water problem still persists... Not sure why it happened again, though...

**Comment by AgonyAunt** [comment]
Buggeration.... ill tell you what, ill try and work on the live version, see if that fixes it. Water is always a pain to deal with.

**Comment by SerenaSV** [comment]
Thanks a lot, let me know if there's anything I should do to help!

**Comment by AgonyAunt** [comment]
Erm, going to need a screenshot. Just taken a look, see no water problem in the build module.

**Comment by SerenaSV** [comment]
Of course!
![nwn2_ss_021215_114136](https://cloud.githubusercontent.com/assets/9882842/6165947/56c673de-b2ac-11e4-903f-02d93f52cd72.jpg)
When last week I checked the build module to see if I did another mistake, I also noticed that nothing seemed out of place in there... yet, in game the water is still visualized one tile south no matter what.

**Comment by miriamchaturvedi** [comment]
You've rebaked this in between, right? Water changes only take effect after the area's been baked.

**Comment by SerenaSV** [comment]
Fixed with last update, I think this can be closed!

@Mimi-Techmouse 
Yes, totally positive I did, I'm a little paranoid when it comes to baking/saving x___x
In local it worked fine, yet in game... Not so much!

Also, the enchanter working bench is still acting up. At this point I think I'll just give up on that and go work somewhere else XD

**Comment by miriamchaturvedi** [comment]
Then we probably didn't update the walkmesh in the main module.

**Comment by AgonyAunt** [comment]
It should have been automatically updated when i staged the module if a new walkmesh was provided.

**Comment by AgonyAunt** [comment]
As for the workbench issue, it has to have the right local variable set on it. Check the workbenches in the bazaar or the lab for an example of what you need to set.

**Comment by SerenaSV** [comment]
Will do, thanks!!

**Comment by AgonyAunt** [comment]
Is this done now?
