### ISSUE TITLE
Male two handed walking animation

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#267]
Sword resting on shoulder for females but male walks with it like a candlestick.

Change male to use female anim?

**Comment by AgonyAunt** [comment]
More suggestions...
http://www.nexusmods.com/neverwinter2/mods/954/?
http://www.nexusmods.com/neverwinter2/mods/953/?

**Comment by miriamchaturvedi** [comment]
Finally took a look at this. Looks like you can't just switch animations between genders, and Nen's animations are. . kinda weird looking.
