### ISSUE TITLE
Kiai smite - CHA bonus not right

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#268]
Kiai smite (the level 3 samurai ability) is not doing what the tooltip says it should. Instead of adding CHA to AB and damage, it seems to be adding a number of dice to damage depending on CHA mod. With +9 to CHA I had 1d10 damage, with +10 I have 2d6, and with +12 I have... 2d4. The AB bonus is also strange, with +10 CHA I am getting +20 to AB, and with +12 to CHA I am getting +22 AB.

I haven't tested the high CHA values in action, so I'm going by the character sheet, but the +9 CHA I did test on monsters and the numbers on the sheet are correct.

**Comment by AgonyAunt** [comment]
Normally remember to catch this, its to do with the effect taking a constant. Works up to +5 using direct CHA bonus to INT values, but beyond 5 you need to add another +5 or +10 to the INT to get the correct constant values you need. That works up to +20 IIRC and then the consts switch back to  dice rolls.

**Comment by Electrohydra** [comment]
Good thing I believe the highest CHA mod you can reach is +16.

**Comment by Electrohydra** [comment]
Fixed scripts are in my file on the Dropbox. You had inadvertently put the +10 bonus to the AB instead of the damage effect.

**Comment by AgonyAunt** [comment]
Awesome
