### ISSUE TITLE
Vampire Dark Form - OP?

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#270]

**Comment by ghost** [comment]
Honestly? Nah. At low levels, yes, but none odd my high level vampires use Dark Aspect because gear is better by that point than the loss of damage. Perhaps for monks.

**Comment by AgonyAunt** [comment]
Its pretty much what i believe as well, but decided to give it a once over and at least consider the comments made.

**Comment by AgonyAunt** [comment]
Out of my hands now, up to staff whether they want to change it. Closing.
