### ISSUE TITLE
Nymph Kiss - document

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#275]
On wiki and in feat description.

**Comment by Electrohydra** [comment]
Done on the wiki. While looking over the code I noticed that the +4 to hit against humanoids is never actually applied to the attack.

**Comment by Electrohydra** [comment]
Added in something that I think will work for the attack bonus (If the target is humanoid, apply a 1-second +4AB effect to the nymph before the touch attack is made). Edited script is in the dropbox under my name.

**Comment by AgonyAunt** [comment]
Thanks Hydra

**Comment by AgonyAunt** [comment]
Done
