### ISSUE TITLE
Beholder Dominate

### ISSUE THREAD

**Issue by Electrohydra** [AgonyAunt/Sigil-City-of-Doors-PW#278]
Still does not work. Looking into it but I can't seem to find the problem. Maybe replace by a charm effect and see if it fixes the problem?

**Comment by AgonyAunt** [comment]
Actually, it was a charm effect and i changed it to dominate to make it more useful.

Try changing the effect to use CutsceneDominate() or whatever its called, although that will allow you to dominate multiple targets. But as a test can be worth it.

Yeah, its a real headscratcher. Put some debug messages in. Check what caster level is calculated as.

**Comment by Electrohydra** [comment]
Added a debug message and switched it to CutsceneDominate to see how it works out. Will assess again when the changes go live.

**Comment by Electrohydra** [comment]
This should be working now. Closing.
