### ISSUE TITLE
Vampire dominate DC?

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#280]
The vampire DC is actually significantly buffed on the server, from what it actually should be, and should likely be nerfed, along with Dark Form. Doesn't effect ANY of my builds, but it does effect many of them out there, and can make a class designed with Vampires to be incredibly powerful, considering the DC they can get out of this thing.

Two fighters go head to head. Vampire uses dominate with a ridiculous DC. Instant win. Great for PvE as well, completely curb stomping devil's will saves, or really any mob that doesn't have immunity. It even bypasses right through spell resist.

The DC is 14 or something in PnP I believe. Which is pitafully weak, so a expected a buff. On the wiki it says it is 10+half vamp HD+Charisma modifier. Instead, it is the full 10+full vamp HD+ charisma modifier. So, even without charisma, the DC comes out to 34 at max level. But since they get a bonus to their charisma it will be even higher, and if they are charisma focus, their DC is disturbing.

**Comment by Electrohydra** [comment]
Indeed, it wasn't using half level. Fixed.
