### ISSUE TITLE
Samurai - all 4 staredown feats do not work (apparently)

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#281]
The samurai feats of staredown, improved staredown and mass staredown don't work. They activate but nothing happens.

**Comment by AgonyAunt** [comment]
Problem is either a type in the 2das or with the scripts not checking right.

**Comment by Electrohydra** [comment]
Think I found it, simple mistake. It was always seeing the target as having been a target of staredown before.

Just going to wait on a live test before closing.

**Comment by AgonyAunt** [comment]
Oh, lol. My bad.

**Comment by Electrohydra** [comment]
Fix is working.
