### ISSUE TITLE
Scrolls of Mnemur

### ISSUE THREAD

**Issue by Electrohydra** [AgonyAunt/Sigil-City-of-Doors-PW#282]
Apparently they are making other abilities act wonky, fey DR stop working, some paladin stuff sticking?

**Comment by AgonyAunt** [comment]
Doubt much can be done with them except to remove them, or players affected to stop using them.

DR stacking is a tricky thing anyway. If you have DR and then a second source, then orginal source can simply be bypassed via the second type of DR.  It should do a logical AND,  but instead it seems to do a logical OR.

**Comment by miriamchaturvedi** [comment]
Do we still plan on getting rid of the Mnemur scrolls someday? Mechanically speaking. .

**Comment by AgonyAunt** [comment]
That was the long term idea... not idea about now.
