### ISSUE TITLE
Death by boots

### ISSUE THREAD

**Issue by Electrohydra** [AgonyAunt/Sigil-City-of-Doors-PW#283]
Yeah, this happened last night. Account krimsongray playing Petal. I was trying to work on an outfit, and while I was working on the boots in the OOC Mirror room, I suddenly just dropped dead. I have no idea why this would happen, but I had no choice but to hit respawn. I ended up going from the OOC room to the Mortuary, XP and gold loss and all. Not very impressed and would like to know how the heck you can simply drop dead working on an outfit BEFORE going into world. I logged out quickly afterwards since I don't want to risk dropping dead again for no reason at the whim of the server. 

Suggestion: Make it so whatevers makes you respawn for free in the OOC room also works in the appearance changer room.

**Comment by AgonyAunt** [comment]
Nice idea. You need to edit the on_respawn script.

Something like ps_repsawn (look at module properties to see script used).

In the script you will see some code that checks the tag of the area you are in and performs different things depending on that.

There should be exceptions for the oocroom, the arena, and the mortuary. Just add an extra one for the appearance changer room.

By the way, no idea why that problem might occur, but if they are CON boots then i'd guess when you are constantly changing their appearance your CON is going up and down, and maybe if you hit a moment of lag, something bad happens with your HP.

**Comment by Electrohydra** [comment]
Fixed.
