### ISSUE TITLE
PC Races with creature weapons should scale with level

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#29]
Rather than messing around giving and taking enhancements and values, simply have a series of creature weapons for each one with increasing values every 5 levels or something that get swapped out.

**Comment by tomekk666** [comment]
:+1:  Just take hints from how Monks scale and let them have Multi-attack. Also, is Greater Magic Fang and the Creature critical spell working with all of them? + Bless Weapon would be a nice touch, I believe it works with current druid ones and with that they can finally damage some thing.

**Comment by AgonyAunt** [comment]
@tomekk666 - its an option. And some races (Lycanthropes) do get multi-attack. And yes, as long as you have creature weapons then all those types of spells work on them.  If you visit the Oarsman and ask for removal, then you lose the ability to receive those types of buffs.  Suppose the wiki should be updated to make that clear.

**Comment by tomekk666** [comment]
Ahh yeah, then they should be bearable as long as the damage scales with HD.

**Comment by ghost** [comment]
Did you have any ideas on what they should scale up to?

Assuming this is a low priority thing I can have a play around with scripting.

**Comment by AgonyAunt** [comment]
The problem is, each race has different weapons, and not all should scale in damage. For example, the Wraith certainly shouldn't get additional damage, but should increase in DC for their drain effect.

This is why its all a rather tricky subject.  Add onto that it requires either making a series of creature templates for each creature, some of them having multiple weapons, or messing around with item properties in some sort of logical manner (and if you know anything about how item properties work from code you'll know what a nightmare it can be to work with).

The alternate method, something similiar to what i've done for Lycanthropes.  A scaling damage bonus applied to the character (which also bypasses DR incidentally - think its something like EffectDamageIncrease) - set it as an ExtraordinaryEffect and reset on rest (that way its not dispellable and people generally rest after gaining a level, so it would adjust if their new level gave them more damage. 

Take a look at the script for lycanthope and vampire forms.  Think its called srr_changes or something like that.

I don't even think you'd have to bother with a feat either.  Probably just hook into ps_rest (or ps_onrest or pc_on_rest????) and do a check for creature weapons and it being a PC.

Something like this:

//... somewhere  in main() function of ps_rest

if (GetIsPC(oPC))
{
    object oCW1 = GetItemInSlot(INVENTORY_SLOT_CWEAPON_B, oPC);
    object oCW2 = GetItemInSlot(INVENTORY_SLOT_CWEAPON_L, oPC);
    object oCW3 = GetItemInSlot(INVENTORY_SLOT_CWEAPON_R, oPC);

   if (oCW1 != OBJECT_INVALID || oCW2 != OBJECT_INVALID || oCW3 != OBJECT_INVALID)
   {
        int iLevels = GetTotalLevels(oPC, TRUE);
        int iBonus = iLevels / 3;  // 1 point bonus per 3 levels.
        effect eDam = ExtraordinaryEffect(EffectDamageIncrease(iBonus, DAMAGE_TYPE_SLASHING)); // this is problematic as base weapon could be same or different type. Another option would be to use DAMAGE_TYPE_MAGICAL.
      ApplyEffectToObject(DURATION_TYPE_PERMANENT, eDam, oPC);
   }
}

Not saying it should be done this way, but its an option.  I'm still not entirely happy with any possible solution, but the one i outline here is probably easiest to implement.

**Comment by ghost** [comment]
Ah, I was thinking along the creature weapon itself being replaced every  5 levels or so with the change being linearly spaced out between starting ECL and 30 being triggered in the same manner as your post level up XP management scrip (seems to be something the cleans excess XP that would otherwise be carried over after level up, I've no idea what its actually called)

I don't know if that is a bigger resource drain than the on rest script and damage bonus. I don't know if your suggestion allows you to add that damage as a Dx amount, it would seem rather dull if you remove most of the randomness of weapon damage rolls as all the base damage is lost to DR and you're just doing the same ExtraordinaryEffect damage each hit. The other thing would be enhancements to hit (these do not seem to work from gloves, the sheet show them but the combat logs do not) Would there be 0 to +5 evenly space out, would there just be damage to compensate, would there be another mechanism (creature uses what would normally be used as an enhacement to perorm an IC ritual to improve it or something) or its simply already acounted for?

I'm really just throwing that out as food for thought. I shall have a play around to see what is possible and what is a pain.

**Comment by AgonyAunt** [comment]
Yes, the ideal variant would be to increase the creature weapons themselves, but then i'd say you're going to have to create a series of create weapons for every race that has them.  A major pain.

**Comment by AgonyAunt** [comment]
Been thinking about this and think i have a good solution that does not require making complex 2das or heavy scripting investigating item properties.

Basic idea is thus:

Playable race gets their base creature weapon(s) with their tags/resrefs. Example: ps_wraith_claw
This is stored in the race 2da and easy to look up.

On level up (script) we try and create an object with the resref of ps_wraith_claw (or whatever the item is called) + IntToString(GetTotalLevels(oPC)).  And this needs checking for every creature weapon slot as well, as some creatures have different weapons in different slots.

So, if the wraith is level 5 it tries to create an item called ps_wraith_claw5.

if the item returns OBJECT_INVALID there is no upgrade available. Move on.

If it returns a valid object, we replace the item in the creature weapon slot and destroy the old one.

Work required:
1) Modification to level up script to check for creature weapons and replace them.
2) New creature weapon templates for those that should have progressing DCs on properties (eg: Wraith and Ghoul are definitely two). Can have them get new ones at levels 5, 10, 15, etc.  Although with the devised system, this can happen at any level, just needs documenting in the creature's TLK entry.

**Comment by AgonyAunt** [comment]
Just noticed, Gargoyles were never given creature weapons anyway, and yet they have no-manual dexterity feat. Also needs changing then.

**Comment by AgonyAunt** [comment]
race_feat_gargoyle and create appropriate weapons. Can be the first test of the system.
Maybe Bauriar as well.

and edit racialsubtypes as necessary as well.

**Comment by AgonyAunt** [comment]
First test with Gargoyles.

**Comment by AgonyAunt** [comment]
Wait for feedback from players on this.

**Comment by AgonyAunt** [comment]
Cere had an interesting idea that may make all this irrelevant.

**Comment by AgonyAunt** [comment]
Cere's work now supersedes this feature.
