### ISSUE TITLE
Frost Giants: Helmet Alignment

### ISSUE THREAD

**Issue by MGoblin256** [AgonyAunt/Sigil-City-of-Doors-PW#294]
On Frost Giants, the horned helmet appears to sit too high above where it should be on the character's head when worn, to the point where the nose guard doesn't cover the nose, and the eye slits are aligned with the giant's forehead instead of the eyes.This bug applies to both PC Frost Giants and NPCs, and appears to be an issue with the model itself.

Attached image highlights the error:
![fghelmetbug](https://cloud.githubusercontent.com/assets/11947047/7142025/d9aeebd2-e281-11e4-962d-48913a262d86.jpg)

**Comment by miriamchaturvedi** [comment]
This is a model error that came with the game. Unless a modeler wants to fix it, I think we're stuck with it. :(
