### ISSUE TITLE
Warlock PRC EB dice

### ISSUE THREAD

**Issue by ghost** [AgonyAunt/Sigil-City-of-Doors-PW#298]
I have a Warlock/Arcane Archer (using the new class version). At Wlk8/AA8/Fellblade1, by my calculation she should have 14 levels of Warlock spell progression (8 + 6 + 0), which should give her a 7d6 EB. However, on the character sheet she only showed 6d6. I took one additional warlock level, and then it showed 7d6, so it seems somehow she has dropped a third CL somewhere in AA1-8 (instead of just at AA1 and AA5). This will prevent her from getting 9d6 by level 23 in time to start taking Epic Eldritch Blast feats.

Possibly related, but I notice that cls_bsplvl_fellblade.2DA has a 0 for indexes 0 and 1, while the documentation suggests that it only loses a CL on the first level. By comparison, cls_bsplvl_eknight.2DA does not have an entry for index 0, while cls_bsplvl_aarcher.2DA appears to assume 0-based indexing. Is this simply a 1-based vs. 0-based indexing issue?

Account name is eidolon and the character name is Eisheth Zenunim.

**Comment by jbgvumkhcs** [comment]
I did some more tests with the Styx the past few days:
Wlk9/AA7/Fellblade1: 6d6 blast dice
Wlk10/AA6/Fellblade1: 7d6 blast dice

So it is definitely dropping a CL on AA7, which is not what I would have predicted from an off-by-one in the .2da files.
