### ISSUE TITLE
Creature Deities Should have Creature Weapon as preferred weapon.

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#305]
e.g., Bahamut, but check new entries as well.

**Comment by Ceremorph** [comment]
(Submitted by WhiteFly in Build Discussion forum)

**Comment by Ceremorph** [comment]
Also Raziel should have bastard sword, not greatsword, as his favored weapon.

**Comment by Alersia** [comment]
I am in favor of combining all these entries into weapon specific ones.

Deity: Ao, Cyric, Mask, Oghma, Tyr
Alignment: Any
Favoured Weapon: Longsword
Description: (references to the five mentioned gods)

**Comment by Ceremorph** [comment]
Done with mine. Your idea is a rework rather than a bugfix, Alersia.
