### ISSUE TITLE
Giant Weapons cannot be buffed

### ISSUE THREAD

**Issue by tomekk666** [AgonyAunt/Sigil-City-of-Doors-PW#31]
Hill Giant cleric could not buff his greatclub.

**Comment by AgonyAunt** [comment]
Bet this is to do with GetIsWeapon() or GetIsMeleeWeapon() function not having the new weapon types in.

**Comment by AgonyAunt** [comment]
Had function name wrong, its IPGetIsMeleeWeapon in x2_inc_itemprops.

Updated that and recompiled scripts for Keen, Weapon of Impact, Bless Weapon, Holy Weapon, Magic Weapon, and GMW.

There may be more scripts that need fixing, but this will do for initial test and hotfix.

**Comment by AgonyAunt** [comment]
No further comments so closing.
