### ISSUE TITLE
Remove Debug Messages from PS_GetEssenceECL function.

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#312]

**Comment by Clangeddin** [comment]
Not only PS_GetEssenceECL, that one is called only once.
The one spamming constantly is PS_GetLevel (that also gets PS_GetEssenceECL)

**Comment by Ceremorph** [comment]
Well yeah, and I got that one too. Hopefully this works without recompiling everything.

**Comment by DMariella** [comment]
This fix for the scry is randomly throwing druids out of wildshape when it fires of, Not every time but every few.
