### ISSUE TITLE
New Psion bugs for Xndar!

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#330]
From Lucadia:
**Energy Wave** Pure Psion. Normal cast and Twin cast do as say, up 13 missiles strike the target, 26 with twin cast. Augment does not give an additional 6 missiles though. 
**Mass Cocoon** the description says 1 hour per level. This appears be lasting 1 round per level. 
**Mass Time Hop** No description that says it respects power resistance, but it appears it does. Been nice if it didnt ,to be the opposite of Mass Cocoon

**Epic focus** for schools not available 
**Epic power point pool** is not available (mentioned on the wiki it exists)
I have both of the feats for reqs and 24 base psion

From Otyugh:
**Psionic Lock** 2nd level power on psion - Can't actually target doors, chests or such to try to lock them. Also, no icon.

From Lucadia:
**Assimilate** Im sure this is far fetched, but at the same time, Assimilate from Psion, which is a melee touch attack has suddenly stopped working at all. Activates but nothing happens.

**Comment by Xndar** [comment]
Epic focus for schools not available - Yes they are, so there may be a feat.2da thing I need to tweak.
Epic power point pool is not available (mentioned on the wiki it exists) - No, this does not exist, so the wiki is wrong and should be amended.

**Comment by Ceremorph** [comment]
Epic Focus requires Progression IX. Updated the Wiki and the TLK to show this, Also added another bug from Othugh.

**Comment by Xndar** [comment]
Yeah, that's the problem. If you change it to require the last progression feat (I think it's 0), it will work properly...as 0 replaces IX after they get 4 level nine powers.

**Comment by Ceremorph** [comment]
I'll let you take care of it then. Added another from Lucadia to the main list.

**Comment by Ceremorph** [comment]
New one from me:

Looking at the script, Ectoplasmic Form doesn't do what the description on the wiki says it does. 

"Your material armor becomes meaningless, although your size, Dexterity, deflection bonuses, and armor bonuses from force effects (such as those gained by inertial armor) still apply to your Armor Class. You can manifest powers while in ectoplasmic form, but you must make a Concentration check (DC 20 + power level) for each power you attempt to manifest."

There's nothing in the script that would affect your armor, and there's a -10 reduction to concentration but nothing about forcing a check. I wound up looking at it because I'm giving a version of it as the emerald half-dragon's Draconic Magic. I have worked out some lines in the script to do the armor thing if you'd like me to share, although I can't see a way for the concentration check without changing every other psionic ability to check for this (or put something in the psionic spellhook I guess).

Also Energy Adaptation, the description says the glow happens after you absorb damage, but it's applied as a constant glow. I fixed this by creating a new OnHitCastSpell item property for my version, let me know if you want this script too.

**Comment by Xndar** [comment]
I don't see a reason to edit anything in Ectoplasmic Form aside from the description (which I've been meaning to do for ages). If the power removes armor bonuses entirely (save deflection and shield) and screws with concentration in exchange for...what...10/+1 DR and some stat immunities, no one will ever use the power and folks that already have it will be pissed about having to rebuild.

Also, Emerald Dragons are all about lore, knowledge and paranoia...why give them Ectoplasmic Form of all things? I'd say Danger Sense would make more sense if it has to be combat oriented, or else a variant on Hypercognition that scales.

...or you can do what I did with the other psionic races, and not give them a power/feat, but rather modify an existing power with a special built-in racial bonus...so emerald half-dragons taking Danger Sense or Hypercognition get a bonus to its effects, etc. Currently Duergar get a bonus to Camouflage and Gith get a bonus to Inertial Armor.
