### ISSUE TITLE
Bardsong/Inspiration Progression for Racial PRCs

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#341]
Just what it says. Firre, Brachina, and Vamp.

**Comment by Clangeddin** [comment]
Found the culprit (in ps_inc_functions) for Firre, the check that should have been for Monadic Deva was being applied to the poor Firre instead, not only this broke the song progression, but also made non-bard devas get a singing progression that they shouldn't have.

As for Brachina and Vamp (maleficus I guess?) are they intended to gain song progression? There's no mention of it in their class description.

**Comment by Ceremorph** [comment]
Yeah, give them song progression but NOT inspiration progression. So far only Firre should have that (and there's two scripts IIRC).
