### ISSUE TITLE
Possible Fix (?) for Favored Soul Favored Weapon Focus Glitch

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#342]
Set a script on level-up to check for this, and if not there grant it.

Temporary fix; will likely need tweaking when Tomekk's Weapon Consolidation project is completed.

**Comment by Clangeddin** [comment]
the glitch concerns weapon proficiency, not weapon focus.

From: http://nwn2.wikia.com/wiki/Favored_Soul

> Deity's Weapon Proficiency
> At level 1, Favored souls gain a weapon proficiency feat that allows them to use their deity’s favored weapon. For example, favored souls of Kelemvor will gain the Exotic Weapon Proficiency feat, enabling them to use a bastard sword. If the deity's favored weapon is an unarmed strike, the favored soul receives Improved Unarmed Strike instead.
> Seems to be bugged; souls of Tyr cannot equip any martial weapons, including longsword. at level 3 with the weapon focus longsword can be equipped, but if you want to dual wield with a shortsword you need to waste a feat on martial weapons
> The bug is that if the "Back" button is used at any time during character creation, a FS will not get their first weapon proficiency feat. If you make a mistake creating the character, choose cancel instead and start over.
