### ISSUE TITLE
Archon Bugs

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#348]
- Aura of Menace stay at the base DC of 18, even with 10 lvls of Trumpet Archon, though every level of the later should give +2
- Trumpet Reveille plainly doesn't work; my PC allies don't get the bonus.

**Comment by Clangeddin** [comment]
1  - Aura of Menace in the script is set to scale with class 999 twice, which I suspect does not exist.
2 - Trumpet of Reveile had the "oTarget = GetNextObjectInArea(GetArea(oPC));" outside of loop, this means that the loop was infinite and eventually breaking.
