### ISSUE TITLE
Greater Heroism

### ISSUE THREAD

**Issue by Ceremorph** [AgonyAunt/Sigil-City-of-Doors-PW#352]
Check if Extend Spell is applying properly to duration.

**Comment by Clangeddin** [comment]
In the script:

"//Enter Metamagic conditions
    fDuration = ApplyMetamagicDurationMods(fDuration);
    int nDurType = ApplyMetamagicDurationTypeMods(DURATION_TYPE_TEMPORARY);"

This means that extend spell is applying properly already, right?
Otherwise I can just rescript manually to double duration if metamagic is extended.

**Comment by Ceremorph** [comment]
Well I was hoping someone would test it in-game first.... just to see if the complaint is legit.

**Comment by DMariella** [comment]
I did a quick test on the test server and the duration was fine for my bard
