### ISSUE TITLE
Review SRs on new races

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#36]
Add new SR feats or use existing 1833 feat?

Or just adjust LAs due to creatures getting too high LA?

**Comment by tomekk666** [comment]
What do you mean new SR feats? Spell resistance?

**Comment by Tamamo-no-Mae** [comment]
What precisely is this issue about? Do you mean that SRs are too low because it's based on character level, which most races don't get as many of? Or...

**Comment by AgonyAunt** [comment]
@tomekk666 - yup, spell resistance. Came out of a discussion on IRC about giving races their actual SR instead of just the stock 10 (or 11?)  + Char level.

Gith for example should only get 5+Char level.

**Comment by AgonyAunt** [comment]
@Tamamo-no-Mae - see previous comment. I basically gave all races with SR the same value.

**Comment by tomekk666** [comment]
I think sticking to the 11+HD is worth it, every race ends up with an SR that can resist spell-like abilities during grinding session well enough.

**Comment by Tamamo-no-Mae** [comment]
I suppose it depends on the race and their level adjustment. Drow get 11+HD, Gith have 10+HD and have fairly similar traits (with Drow in the clear lead), for instance, and both have LA+2.

**Comment by AgonyAunt** [comment]
@Tamamo-no-Mae - actually i think that is an error on my part. They all get the same Drow 11+HD. So i need to change descriptions where i wrote 10+HD.

@tomekk666 - yeah, not quite my thoughts, but basically it makes area design with monsters easier. Either they have racial SR which is the same for all races with, or they don't (unless they have SR items).  On the other hand, its not canon... which reminds me, this should also be tagged a Lore vs Mechanics point as well.

**Comment by AgonyAunt** [comment]
Standardised descriptions to be 11+HD
