### ISSUE TITLE
Allow Succubus To Be Bards

### ISSUE THREAD

**Issue by spbrockmann** [AgonyAunt/Sigil-City-of-Doors-PW#380]
Because Lilitu can be bards in lore

Forum post: http://s13.zetaboards.com/nwn2planescape/topic/9145418/1/

**Comment by spbrockmann** [comment]
Dropbox link: https://www.dropbox.com/sh/2c11j8u6jfeznro/AAA5DXaC9aklC5XXmsYG8XXZa?dl=0

**Comment by edmaster44** [comment]
Done.
