### ISSUE TITLE
Vampire Gaseous form can be hit by (magical?) weapons

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#39]
Check Gaseous form of Eladrin as well

**Comment by Tamamo-no-Mae** [comment]
Confirmed that vampire gaseous form can be hit by magical weapons. A nonmagical weapon was unable to deal physical damage to a gaseous form vampire (damage reduction absorbing 30 and letting 0 through), while a magical weapon from the same wielder could (damage reduction absorbing 10 and letting 5 through).

**Comment by AgonyAunt** [comment]
Thanks. Looks like ill have to change the DR type then.

**Comment by AgonyAunt** [comment]
Was 100% immunity to physical. Looks like this is overcome by magical weapons. Tried to change this to 100% immunity to Pierce + 100% immunity slash + 100% immunity bludg.

See if that works better.

If not, then will have to change it to be a feat which gets added when they change form although not sure if that will fare better.

Need confirmation of fix.

**Comment by Tamamo-no-Mae** [comment]
Confirmed that a magical weapon was stopped by the damage resistance of gaseous form. (More than 10 and the damage reduction absorbed 0, so it was the resistance from gaseous form, not the racial DR 10/silver.)

**Comment by AgonyAunt** [comment]
@Tamamo-no-Mae  or @tomekk666 - can one of you confirm whether or not the fix that went in today now fixes this?

Apologies, didn't read last comment.  So... its fixed?

**Comment by Tamamo-no-Mae** [comment]
As far as I can tell.

**Comment by AgonyAunt** [comment]
Awesome! Thanks!
