### ISSUE TITLE
Stone scorpion venom bypasses immunity to poison

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#42]
In the umber hulk caves in the earth plane, the stone scorpions can seemingly poison characters immune to poisons. The attack hits, the poison immunity message triggers, but the character can still be hit with a slow effect (which is what I presume the venom is). If this slowing is actually a side-effect and they have a separate poison and I was mistaken, please close this issue.

**Comment by AgonyAunt** [comment]
I'd guess it should be linked to the poison effect, but the check for poison immunity is only being made on the poison itself. Thanks for the report.

**Comment by AgonyAunt** [comment]
Ah, they are two separate effects on the same creature weapon, therefore they cannot be linked.
So going to have to go down as a Can't Fix.
