### ISSUE TITLE
Kamal's reskinned mindflayers

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#43]
http://neverwintervault.org/project/nwn2/model/kamals-mindflayer-reskins

Oh yes!

Check size though, don't want to increase HAK size too much.

**Comment by tomekk666** [comment]
Tint maps are nice, but they look very, very low-res to me. :-S

**Comment by AgonyAunt** [comment]
Also this: http://neverwintervault.org/project/nwn2/model/illithid-lord-model

**Comment by AgonyAunt** [comment]
@tomekk666  - same as regular model i'd guess. Kamal_ does good work usually. Probably the pics don't do them justice.

**Comment by tomekk666** [comment]
Yeah, they're obnoxiously pixelated so I guess its a low res image. I say go for it, won't hurt anyone... though Illithid's ECL is something else :p

**Comment by AgonyAunt** [comment]
Tested, looks good, adding.
