### ISSUE TITLE
Create Greater Undead - increase duration

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#47]
Should we?

**Comment by tomekk666** [comment]
Its one of the only wortwhile summons, why not?

**Comment by AgonyAunt** [comment]
heh, perhaps.

**Comment by Tamamo-no-Mae** [comment]
As it is now, Create Greater Undead's summon doesn't die before its duration runs out so much as its duration runs out before you finish buffing it.

Edit: erk, sorry, clicked the wrong button.

**Comment by AgonyAunt** [comment]
@Tamamo-no-Mae - That bad? LOL. Ok, i'll definitely take a look at it then.  And getting carried away closing issues? Hehe.

**Comment by AgonyAunt** [comment]
Decided against it as will be implementing the summoner PrC. All summon spells will be affected by this class who will get a feat providing longer summon durations.
