### ISSUE TITLE
Lycanthrope hybrid and beast DRs don't match descriptions

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#48]
Description says DR AS10 for both.  Design gave 5 for Hybrid and 10 for Beast. Apparently Beast only gets 5.

Needs descriptions bringing into alignment with mechanics and decision making on what is right. Also figure out why Beast form only gets AS5.

**Comment by tomekk666** [comment]
Bring both to ten. Beast should be good for a quick getaway and hybrid for fighting IMO.

**Comment by AgonyAunt** [comment]
That would be in line with SRD....

**Comment by tomekk666** [comment]
And is that a bad thing? Giving the combat form the lower DR is not exactly great logic IMO.

**Comment by AgonyAunt** [comment]
Nope, it would be a good thing. I just question whether i want to do that.

**Comment by AgonyAunt** [comment]
Just changed description for the moment on Beast form, as there are some tricky aspects to applying DR on existing DR the race gets.

Merging with issue #86
