### ISSUE TITLE
Werewolf and wererat ability adjustments are enhancement bonuses

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#49]
To clarify, the ability adjustments from going into hybrid or full beast form are added as enhancement bonuses. In other words, they do not stack with gear, and thus can and will be rendered irrelevant. This makes their level adjustments simply not worth the benefit. Added to bug and feature request because I'm not sure if this was a bug or intentional.

**Comment by AgonyAunt** [comment]
Not only intentional, its the only way it can be done. Closing.

**Comment by Tamamo-no-Mae** [comment]
Sadface. :<
