### ISSUE TITLE
Vampire gaseous form has incorporeal racial type

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#50]
Vampires in gaseous form are not incorporeal. Also, this makes it so that vampires in gaseous form can be harmed by negative energy spells and cured by positive energy spells, and cannot be turned.

**Comment by AgonyAunt** [comment]
Thanks. Thought it made sense for them to be incorpreal, but you pointed out a real problem with this idea, so will change it to undead.

**Comment by AgonyAunt** [comment]
Changed
