### ISSUE TITLE
Vampire gaseous form can deal physical attack damage

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#51]
It is incredibly minor, 1d3, but still there.

**Comment by AgonyAunt** [comment]
Interesting, shouldn't be anything. The creature weapon has No Monster Damage property.  Ill double check but this may just be a game engine bug.

I can try lowering the STR on the form... maybe that will offset it a bit.

**Comment by Tamamo-no-Mae** [comment]
Nah, don't lower the STR. It's already pretty low as is, too much farther and it'll start being Dark Discorporation's same problem. I'm pretty sure there's a reduced damage property somewhere though--if No Monster Damage isn't working, try No Damage or -10 or so bludgeoning to lock it at 1 even if it got a buff. 1 damage is still damage, but... well, it's so nonexistent it's really not worth considering. Maybe useful against the bats in the inn basement, not really anything else.

**Comment by AgonyAunt** [comment]
Well, 1d3 is also practically no damage, although it can crit.  But will see what i can do.

**Comment by Tamamo-no-Mae** [comment]
It's not too big of an issue, just thought I'd mention it as a bug.

**Comment by AgonyAunt** [comment]
Letting this issue go, its too minor to bother with.
