### ISSUE TITLE
Mechanus spawns not working

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#52]
I promised Xndar i would look at this when i got the chance.

Also needs portal hooking up when spawns fixed.

**Comment by AgonyAunt** [comment]
Never got chance to look at this, so now Xndar is back, they can try and figure it out.

**Comment by AgonyAunt** [comment]
@Xndar - i've not got the spawns working, but found at least one cause of it not working.

When you set the names of the spawns you used the full resref including the trailing number (in this case 1) in the trigger. As you also included a HIGH setting of 4 IIRC and a LOW setting of 1, if your (or any) test character had an ECL of > 1 then no spawns would occur.

There are two ways of dealing with only having 1 level of spawn in an area.  Either create versions 2 and 3 of the spawns (ie, with resrefs of monster1, monster2, monster3) and make sure the trigger just references the base monster (ie: monster) or create just the monster1 version and set the LOW variable to anything greater than 30, ensuring that only the version monster1 will ever try and be spawned.

Now ill move onto putting in some debugs into the spawns script and see exactly where its failing now, but its either going to be some variable you are missing on your triggers, a tag or a resref not matching, or just possibly, the extremely long length of your WP tags with multiple underscores... i'm not sure the game engine can handle such long tags for WPs and i seem to recall multiple underscores in a tag can also cause things to go strange.

**Comment by AgonyAunt** [comment]
Oh, and also, i found a non-combat modron that was spawned. I hope that is being spawned via on_enter script and not static, otherwise i will slap you upside the head! And ill be checking you attached the clean up script as well.

**Comment by Xndar** [comment]
If you are referring to the guard modron that warns folks that the other areas are dangerous, no, it does not use an on_enter script, as I didn't know such was necessary. I will try messing with the LOW, HIGH stuff as you've mentioned. If that is the case, then this would explain why it wasn't firing.

**Comment by AgonyAunt** [comment]
Spawns are working now.  That guard modron needs adding to an on_enter script and area needs clean up script attaching if not (ill check it out).

Ill get this done. 

Also ill post on builders forums to discuss where we should have the portal.

**Comment by Xndar** [comment]
Just re-posting to make sure you see; I've uploaded an updated version of the Mechanus area which should be named properly and have the appropriate WP added in. For the Infinite Staircase portal-labeling tweak, do you want me to do that with my version and send it your way, or would you rather handle it?

**Comment by AgonyAunt** [comment]
Thanks.
