### ISSUE TITLE
Adjust Limbo spawns CRs and chests

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#53]
One for Mimi when she gets the chance.

Reports were spawns CR were too low for difficultly meaning not enough XP.

**Comment by miriamchaturvedi** [comment]
Issues to fix: 
- Spawns CR too low
- Chests need more treasure
- Chests shouldn't declare the amount of gold they're generating
- Possibly need more monsters

I will look into fixing these in the next month.
