### ISSUE TITLE
Liches and their phylacteries

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#54]
I would like to ask why the lich has such a high level adjustment (+6!), and if there is any way to integrate their phylactery and revival abilities into their racial traits. While it might be a bit iffy to venture into death penalty leniency for a single race, the ability of a lich to get back up after you strike it down is its defining feature. You kill them, and they just don't die.

**Comment by AgonyAunt** [comment]
@Tamamo-no-Mae - Hmm... we could add the same ability the Spirit Shaman has. The one that restores you to life.  Could even keep activating it. Would of course be a real pain to players who are stuck being killed over and over again though.  So perhaps once per day with full heal would be good.

As for +6, well, its pretty nice for casters as races go, but yeah, maybe a little high, so some extra benefit wouldn't be a problem i think.

No way to integrate the phylactery as the source of the regen, but could make the regen be contingent on them possessing their phylactery. Currently it cannot be removed from the owner, but it could make a nice plot device if it could be.

Thoughts?

**Comment by tomekk666** [comment]
+6 is way too high considering their mediocre stats and the appauling HP they will achieve as a wizard or such. I'd suggest 5 at most so they can still reach Epic Caster DC+3 via practiced... but even that is too high.

**Comment by Tamamo-no-Mae** [comment]
"So perhaps once per day with full heal would be good."
Or have it on a cooldown? Wait at least one minute between triggers, gives ample time to choose to respawn. Given that liches are primarily casters, that's probably not as bad as it sounds, since they'll lose their buffs on death. Once per day could work though. Aside from that, I would suggest either lowering their level adjustment to +4 to be in line with P&P, maybe +5 at most, or giving them some other kind of bonus.

**Comment by AgonyAunt** [comment]
I think +4 could be an option with this race or +5 with the auto-heal.

Cooldown could be good as it would then avoid the whole death/heal/death/heal issue.

Only problem is it usually activates on rest so ill have to tweak it to work differently.

**Comment by AgonyAunt** [comment]
Changed the phylactery so once per day they can activate it to get a full heal on death.  Players will need a full rebuild though to get the modified version or else it needs to be swapped out by a DM.
