### ISSUE TITLE
"Faithless" tattoo (very likely) provides no resistance to turning

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#55]
From experience, I've found that the tattoo providing +15 turn resistance... does not do that. Turning rates don't seem to change at all.

**Comment by AgonyAunt** [comment]
I was always suspicious of that myself although i never played any race that could be turned. I never saw anything in the code to support it, so always presumed it was something in the hard code that handled it.

**Comment by AgonyAunt** [comment]
From the NWN1 wiki: Turn resistance applies only to non-player characters as neither the item property nor the effect affects player characters. If a player character has taken on an outsider race (e.g. outsider shape), the spell resistance will still emulate turn resistance.

So instead, this tattoo needs changing to have a scripted effect on it that uses EffectTurnResistanceIncrease

Problem is, as tattoos are auto activated as having properties, not sure whether this effect would kick in or not when you logged in automatically.

It may have to work by having an activation script associated, set a spell ID related to it (SetEffectSpellID - reserve a row in spells.2da to make sure it isn't used in future) and check for that spell effect in the script to make sure it hasn't already been applied. Effect should be made supernatural, so will last until player logs off/reset.

**Comment by AgonyAunt** [comment]
As this requires a complicated solution, removing this tattoo from the conversation so can no longer be bought. Will add change to next update.
