### ISSUE TITLE
Assassin spellcasting as arcane archer qualification

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#56]
Would it be possible/reasonable to let Assassin qualify for Arcane Archer past a certain level, since the Assassin PRC uses prepared arcane spells?

**Comment by AgonyAunt** [comment]
That could be tricky due to how requirements are handled. Ill take a look at some point. See if its doable.

**Comment by AgonyAunt** [comment]
Looked into this. Its definitely tricky as in the requirements there is no way we can match current requirements with Assassin.

Currently it checks for Arcane Spellcasting 3rd level.
![image](https://cloud.githubusercontent.com/assets/8188251/4089293/e1abcd12-2f69-11e4-8718-f98d08c09099.png)

That would have to removed and replaced with new lines that instead check for specific class levels, ie:
CLASSOR WIZARD 1 (Wizard i think needs to be class row ID from classes.2da by the way)
CLASSOR SORC 1
CLASSOR BARD 4 (i think)

However, having considered it, i think i'm saying no to this change.

If in the future, we implement custom spellbooks (eg: http://neverwintervault.org/forums/neverwinter-nights-2/nwn2-custom-content/spellbook-rework) then i think we can consider this, and then we can also give other classes proper spellbooks as well.
