### ISSUE TITLE
Word of changing forms

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#57]
Would it be possible to change what forms Word of Changing uses? Maybe let warlocks talk to Styx in the OOC room to get a feat or cursed item that WoC checks for. This would let players use WoC while RPing pacts that... you know, are not infernal. A demon would never give a devil's form, and there are a lot of fey, celestials, and eldritch horrors who probably have their own tastes.

**Comment by AgonyAunt** [comment]
Actually, if i were to do this, i'd make it alignment based. Its one of those things that has been considered before and just so low priority its never got dealt with.  But now we have GitHub at least we won't forget. ;)

**Comment by tomekk666** [comment]
Do starpact warlocks become an indescribable mass of tentacles?:p

**Comment by AgonyAunt** [comment]
LE/NE keep Horned Devil. CE gets Hezrou. CG/CN gets Ragewalker
