### ISSUE TITLE
Cowl of Warding bonus vs Mind Affecting

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#61]
Doesn't appear to be working, at least against fear effect from Horned devils.

Could be a problem with either property or devil effect.

Needs a quick test module setting up to check dice rolls against both the fear effect and item properties.

**Comment by Tamamo-no-Mae** [comment]
Alright, let's see...
Will save without Cowl of Warding vs. Horned Devil Elite fear effect: +26
Will save with Cowl vs. fear effect: +26
Will save without Cowl vs. Hold Monster: +30
Will save with Cowl vs. Hold Monster: +30

I'm going to go ahead and say it's the Cowl's problem. The Horned Devil Elite's fear effect is definitely tagged as mind-affecting.

**Comment by AgonyAunt** [comment]
Right, so some sort of problem with the item property in general then it looks like.  not sure we can do anything about that except change the item to do something else.

**Comment by AgonyAunt** [comment]
Just noticed, item description does not match, as it says it also acts like freedom of movement. I think its just best to pull this item from the game.

**Comment by AgonyAunt** [comment]
Changed item properties instead. Now gets SR12 and can cast Mind Blank 1/day and Lesser Mind Blank 3/day.
