### ISSUE TITLE
Better renaming widget/ui

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#63]
Er Nano Infame:
can items renaming window (the one showing up using DMFI tool) be improved ? more space, more alph numeric characters useable, colours and all?

**Comment by AgonyAunt** [comment]
Technically yes. Original idea was not to allow people to make items that look special when they are not so as to keep the uniqueness of special items.  Will think about whether we want to allow this.

**Comment by AgonyAunt** [comment]
Changed to max length of 64 characters and can use special characters. Hope people don't go too silly with it.
