### ISSUE TITLE
Belt models on appearance changer

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#64]
A. Thereal:
I'm certain this topic has been raised before, but can we please allow access to belt models on the appearance changers? I know for a fact that the appearance changer SCoD uses is capable of accessing belts - I've done it on other servers via the same system.

I know this would make a lot of people happy.

http://z13.invisionfree.com/nwn2planescape/index.php?showtopic=9254

**Comment by AgonyAunt** [comment]
As stated on forums. Need to know of a server which has this option and would need to integrate it, not something i'm sure i can do.

**Comment by miriamchaturvedi** [comment]
Its part of the standard xp_craft as of the past few years (assuming that plugin is hosted elsewhere now that the vault is dead). I could try implementing it when I'm done with my other projects?

Sadly, you can't tint the belts even if you can change them. :(

**Comment by AgonyAunt** [comment]
I think its probably hosted on nwnx.

Would need to check to see whether the dupe item fix is in place and other changes we made locally... so best if possible to integrate.

**Comment by AgonyAunt** [comment]
Understand still work to be done, but i think we can close this now and leave it to Mimi to refine as she will.
