### ISSUE TITLE
Celestial wolverine question should have nonlethal resolution as an option

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#65]
For the quest, you should be able to make a survival check upon encountering it to see if you can get it back out through the portal without killing it. This would make it possible to resolve in a merciful, good-aligned way.

Suggested layout:
Spawn the animal as neutral/friendly, automatically trigger dialog with three options.
1: Attack/defend yourself/something.
2: If the player has belladona, make a survival check to get it led out and into the portal safely.
3: If the player has belladona and is a druid and/or a nymph, allow them to lead it out into the portal safely without a check.

**Comment by AgonyAunt** [comment]
Interesting idea. But yeah, one of those things for when nothing much else to do, or perhaps for a new developer to try and cut their teeth on.

**Comment by AgonyAunt** [comment]
Closing as nobody has shown an interest in this.
