### ISSUE TITLE
Acid head arrows, freezing arrows

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#67]
Acid head arrows seem to have a price locked at 0, despite their effects being directly superior to acid arrows. (Acid arrow: +1d6 acid; acid head arrow: +1d8 acid, blindness DC 16 5% for 5 rounds, wounding DC 20). 

Freezing arrows have the on-hit property: "Bad Strref Level 5".

**Comment by AgonyAunt** [comment]
Closing. First issue is intended. Second, not sure, but anyway all items will get reviewed when economic overhaul goes ahead. Any bugged/broken items will be fixed/removed at this time.
