### ISSUE TITLE
Word of changing racial type is djinn

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#68]
It's not even remotely important as far as bugs go, but it really looks silly on the character sheet. Form and stats are fine, just that tiny little bit.

**Comment by AgonyAunt** [comment]
That is strange!

**Comment by AgonyAunt** [comment]
Same problem as issue #82 - DefaultSubRace column was set to a playable race instead of Outsider sub-race. Changed on all other races now.
