### ISSUE TITLE
Increase stack size for throwing weapons

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#70]
Because 50 just get burned through too quickly.

Possibly allow stacks to be much bigger.

**Comment by Tamamo-no-Mae** [comment]
I don't see much of a reason why not. All having ammunition split into small stacks does is force people to fill up chunks of their inventory if they're ranged, or get a bag and only have a few at a time. 50s instead of 99s for thrown weapons is even worse.

**Comment by AgonyAunt** [comment]
Its also worse for performance.  A single stack of arrows of size 100000 takes the same memory as a stack of arrows of size 1, but two stacks take twice the memory. Granted, its tiny, but when you have lots of and lots of them, then it starts to add up.

**Comment by AgonyAunt** [comment]
Increased max stack size to 500. Care should be taken now when creating new item templates for throwing weapons as they will default to 500 and therefore should be manually adjusted downwards. Existing templates should not be affected _crosses fingers_
