### ISSUE TITLE
PC Tools with certain races

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#71]
Lacking details at the moment, but looks like using certain PC Tools could cause irreversible crashes with certain races. 

Case in point Myconid.

Still trying to get more details.

**Comment by Tamamo-no-Mae** [comment]
What does 'irreversible crash' mean? Will continually crash if trying to log onto that character again? Well, either way, I'll make a test myconid (or five) and spam PC tools options and tell you which ones, if any, trigger crashing.

Edit: I tried just about every conceivable option with the PC tools, but no problems. Must be something else to it... I'll wait until we get more info on this.

**Comment by AgonyAunt** [comment]
Yes, i think it might be appearance changer. What happened with the Beholder is wearing any armour other than the ones provided by the special shop in the OOC room would cause a client crash (server would remain).

Anyway, their character was fine in the end, so not sure what was happening.

Thanks for the testing.

Still waiting for more info from the player.

**Comment by AgonyAunt** [comment]
No longer urgent as obviously not as bad as first though.

**Comment by AgonyAunt** [comment]
Apparently it was the mandolin VFX that caused the crash.

**Comment by AgonyAunt** [comment]
No further reports, closing for now.
