### ISSUE TITLE
Level 10 Blackguards to get Epic Fiendish Servant

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#75]
Incentive to take 5 levels of BG? Not too much more powerful than the regular one though so as not to unbalance. Keep in mind BGs can get Divine Might and more.

Anyway, from Phantom Hermit:

New feat idea:

Requirements: 10 levels blackguard, epic levels

Summon an Epic Vrock for 24 hours.

as per

http://nwn.wikia.com/wiki/Epic_fiendish_servant

Dunno if it could be coded as a pet that raised in levels with character levels, but that is something to consider as well.

Was thinking about blackguard and a reason to take more than three levels. Could not think of any. Shadowdancers have nifty stuff. Pale master summons are powerful. An eryines does not really seep darkness and destruction- nor does it really scare or pose as much a threat as a master of evil should be able to call forth.

Thoughts?

**Comment by Ceremorph** [comment]
One of the biggest problems with blackguards in NWN2 is lacking the spell progression that the PnP version has, while most of its features past L3 really don't fit the levels you're actually gaining them at (I mean seriously contagion?). Might be cool to simply let the fiend summon progress to better fiends and/or times per day with levels, maxing out  at L10.

**Comment by AgonyAunt** [comment]
Yes, no problem with this. Possibly make the summon alignment based as well if we don't have that already. Never played a BG on our server.

**Comment by Xndar** [comment]
I think it is currently alignment based, with LE getting an Erinyes, and everyone else getting a Succubus.

**Comment by AgonyAunt** [comment]
Decided against. Closing.
