### ISSUE TITLE
Succubi start with Scent instead of DR 10/Cold Iron

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#77]
In race_feat_succubus.2da, line 1 is
1 drci10 2178 (FEAT_SCENT)
when it should be
1 drci10 2290 (FEAT_DR_CI10)

**Comment by AgonyAunt** [comment]
Thanks. Ill take this one then.

**Comment by AgonyAunt** [comment]
Fixed
