### ISSUE TITLE
Troll Race - not vulnerable to Fire and Acid

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#8]
Acid vuln feat needs creating (see existing Fire Vuln feat).

Add both feats to racial 2da. Update race description TLK.

If desired that any existing trolls retroactively get these feats then will need to edit pc_onmodload (or whatever its called) to check race, then check if they have these feats, and if not, add.

I recommend not to bother.

**Comment by ghost** [comment]
I've done this other than the tga file for the new feat. Is there somewhere you use as a source for these?

What is the policy with regards to feat.2da/spells.2da/scod.tlk entries as I assume there may be multiple people working on this? is there somewhere the most recent version lives?

**Comment by AgonyAunt** [comment]
@lukehall - As far as i know, nobody is modifying any of those files at the moment, but Xndar has some rows reserved. I've just added you to the builders group.  You can see which rows they have reserved here: http://z13.invisionfree.com/nwn2planescape/index.php?showtopic=9081&view=findpost&p=22676588

Use your own copies of 2das, tlk from your my documents\neverwinter nights 2 folders. I usually copy your entries into the master version, so all i need to know is which rows you have changed/added in which files.

One day we may change to using github for source control, then this will change.

As for the TGAs, basically i just googled for images trying to find something that looked appropriate. I use GIMP for editing TGAs.  If creating images is not in your comfort zone let me know, ill make the image.

**Comment by ghost** [comment]
Completed and added to dropbox

**Comment by AgonyAunt** [comment]
Thanks, i actually missed this notification otherwise i'd have got it in today. Sorry about that.

In future please make scripts or anything else that goes into the build module as an ERF.  Ill deal with it this time.  Also note here which tlk/2da rows you have reserved, can save me hunting it down on forums.

Ill reopen the issue for the moment until i get it added to the main module.

**Comment by ghost** [comment]
Sorry about that

**Comment by AgonyAunt** [comment]
No worries. Using GitHub as the tracking tool is still new, it will take a little while to make things work smoothly between contributors.

**Comment by AgonyAunt** [comment]
@lukehall - hot tip by the way. When you edit a 2da, then use something that allows you to save the 2da with spaces converted to tabs or so it just uses single spaces. I use Excel for editing 2das.

This way for example, spells.2da is 670kb instead of 2.1Mb ;)

**Comment by AgonyAunt** [comment]
@lukehall - oh dear, sorry, got to bounce this back to you.  Check your entry for the feat is spells.2da.  Looks like you copied in the line from feat.2da rather than the spell entry.

I could fix this, just copy an existing feat entry from spells.2da and change the references and stuff, but its a good learning experience for you ;)

Also, the 2das themselves, they are incorrectly formatted. There is a free column (or space) at the start of each line. If i were to use this 2da in game, it would possibly fail to load.  What were you using to edit the 2da?

**Comment by ghost** [comment]
Sorry about that, looks like i screwed up when I moved the entries and I was using the toolset to edit the 2das. I have redone them from scratch using libreoffice calc. I also created and erf of the script.

2373 in feat.2da
1381 in spells.2da
1701 and 1702 in SCOD.tlk

Assuming the wiki has the correct stats for trap damage It has been tested again and confirmed working.

**Comment by AgonyAunt** [comment]
Oh right.. .yeah, toolset is terribad for editing 2das.

Erm, what does trap damage have to do with anything?

**Comment by ghost** [comment]
I used them to test the increased damage taken from both fire and acid. I could not find a command to infict damage to confirm this with so had to resort to the low tech solution of filling the OOC room with minor acid and fire traps and trigger them to see if I could get a dmage greater than 2d8 for acid and 5d6 for fire IIRC.

**Comment by AgonyAunt** [comment]
Oh, nice idea.

**Comment by AgonyAunt** [comment]
There are ways to script it to happen though, or give a monster a flaming weapon for example ;)

**Comment by AgonyAunt** [comment]
Hehe, you gave me an ERF this time, but had messed up. I guess you manually created the ERF and copied the file in... the NCS version, which is the compiled version and no good for importing.  You should have copied the NSS.

What you should do is export things from the toolset, its the safest way.

Anyway, don't worry about it, i simply created the script myself. ;)

Its a learning process getting used to how things should be done.

**Comment by AgonyAunt** [comment]
And you still had the wrong edit in spells.2da, you had copied the fire feat entry.... ill fix that as well...

**Comment by ghost** [comment]
Sorry copied the wrong spells.2da file, correct one is there now. I'm not sure what I did with the ERF, I did it from the toolset again I'll review the process

**Comment by ghost** [comment]
Oh right, I tried to add both but it said one was already present and I overwrote it with the other. I shall remember to put just the NSS in next time

**Comment by AgonyAunt** [comment]
Just use export from within the toolset, its the most reliable way.... then next time ill teach you about sanitizing ERFs

**Comment by AgonyAunt** [comment]
Ready for update
