### ISSUE TITLE
Pseudonatural template

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#81]
No, wait! Don't leave! I meant the Lords of Madness one!

Ahem.
Especially given the Far Realms business around now, what about making a pseudonatural creature race option? Or half-farspawn. The alternate form appearance could be made from a slightly modified Evard's Black Tentacles VFX. The rest of the stats aren't difficult to get, to my knowledge. Maybe use Aberration for the racial type here, even though they're actually Outsiders. (Like how Githyanki and Githzerai are both Humanoids, not Outsiders.)

(Edit: I'm very doubtful this will happen, but I'm trying to throw out any notable ideas I come up with just in case any of them turn out well.)

**Comment by AgonyAunt** [comment]
Nah, the Far Realm is overused as it is. Its meant to be something out there, not confirmed, on the edge of everything.  Its meant to be a mystery.  Making a mechanical representation of it is going to far.  And besides, plenty of other races out there that could be added well before something like this.
