### ISSUE TITLE
Pale master summons as companions

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#83]
As it is now, Pale Master is pretty terrible. What about making their undead summon into the animal companion/familiar slot? Would be a good way to give them an ability related to necromantic prowess (especially if Create Greater Undead's duration is increased).

**Comment by AgonyAunt** [comment]
I'd say this is something that would be done as part of a possible future improved familiar update where pale masters could chose to have an undead familiar.

So ill close this and add a note to issue #66
