### ISSUE TITLE
Grafts

### ISSUE THREAD

**Issue by Tamamo-no-Mae** [AgonyAunt/Sigil-City-of-Doors-PW#84]
They just seem like an interesting and very fitting thing to implement for Sigil. And would make more sense than tattoos.

**Comment by AgonyAunt** [comment]
Grafts though would really require a model to display.  Tattoos can be covered up... how you going to hide that extra arm?

**Comment by Tamamo-no-Mae** [comment]
I was meaning the graft items from various books. Many of them don't have an external appearance.

Just, you know, no silthilar grafts. Those things are OP.

**Comment by AgonyAunt** [comment]
Right... well, its something to consider, but low priority.

**Comment by AgonyAunt** [comment]
As nobody shown interest, closing.
