### ISSUE TITLE
Make area transitions with convos 1 liners

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#90]
eg: Abyss, Minaurous, and lots of other places.

With a 1 line convo no dialog box will appear.

**Comment by Xndar** [comment]
I will double check this later on today, but when I was putting together the Find Portal function for the Gatecrasher, I noticed that when I reduced the conversation tree to a 1 liner with an action attached, that the action didn't fire correctly. When I added a second line, and attached that same action (no edits) to the second line, it worked perfectly.

In other words, I don't think it is possible to reduce the portal convos to 1-liners while maintaining their functionality. Will do more testing, but I am pretty sure that is why they are currently the way they are.

**Comment by AgonyAunt** [comment]
Ah, ok. That's a shame. Then probably close this.
