### ISSUE TITLE
Torc of Celestial Glory set bonus not working

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#91]
The set bonus doesn't activate when you have the Torc, and the Platinum and Silver rings. I had the old bugged version with the Good Domain Powers feat which does nothing, and had it swapped out for the fixed version that gives +6 save vs fear, but even with that one the set never activated, and swapping out a ring just turned the Torc back into the version with the Good Domain Power feat.

**Comment by AgonyAunt** [comment]
One for Cere to deal with.

**Comment by Ceremorph** [comment]
Okay, I've set up an account. No idea how this works or how to assign myself something...

**Comment by Ceremorph** [comment]
Well at least I have figured out what happenned. Someone updated the Torc's blueprint earlier this year with the change you mentioned, but didn't bother to go in and fix the script. I think.

**Comment by Ceremorph** [comment]
Boom! Think I got it.
