### ISSUE TITLE
Feats to offset racial LA

### ISSUE THREAD

**Issue by AgonyAunt** [AgonyAunt/Sigil-City-of-Doors-PW#98]
Basic idea is allow feats to be taken which can offset racial LA.

There is the level up script and the XP script, as well as perhaps some functions in ps_inc_functions that might need adjusting to take this into consideration (if editing ps_inc_functions, remember to do a full compile as it touches on many of our custom scripts).

Need to think about this.

**Comment by tomekk666** [comment]
I just had an idea...

Feat 1: Gain Caster levels equal to half your LA.;  Feat 2: Gain an AB boost equal to half your LA. Suddenly a Fire Giant can get comparable attack bonuses to an ECL 0 race and a djinni can get comparable CLs aswell.

**Comment by AgonyAunt** [comment]
Caster level is very tricky to handle. AB boost is possible, but would contribute to cap.  Probably not best way to handle this.

**Comment by AgonyAunt** [comment]
Closing as now made change to how XP calculations are made for LA races. I know its not the same as was required here, but i think we can let this issue rest for the moment, see how things go.
